= Handling Old Comments
:authors: Marcos Benevides
:state: ideation
:labels: database,github,pull_requests
:source-highlighter: highlight.js
:toc:

== Status

Ideation.

== Goals

. Document how comments work as of now.
. Aggregate community suggestions.
. Describe possible implementations of https://github.com/terrateamio/terrateam/issues/116[terrateamio/terrateam#116].
. Discuss trade-offs of each alternative.

== Background

Currently, the Terrateam application posts comments in response to specific user events (triggered by commands such as `terrateam plan`, `terrateam apply`) on pull requests.

. Application comments are not currently tracked or stored in our systems; we rely solely on GitHub/GitLab as the source of truth.
. There are ways for a change with multiple directories to cause comment sprawl over a pull request.
. We are still unsure on how to relate comments with `work_manifests`
. There used to be a mechanism to deal with oversized comments, but it seems to be disabled now.
. We have no mechanisms to group related comments together nor can we provide a consolidated summary.

=== Community Suggestions

The community has raised multiple suggestions around improving comment handling, mostly to reduce noise on pull requests. Some suggestions include:

. Introducing a _"status/summary"_ comment that acts as a consolidated view of all operations on a PR, reducing fragmentation of information and making it easier for reviewers to assess the state of infrastructure changes.
. Anchoring a single comment that is updated over time, rather than posting multiple new comments for each operation.

TODO Add pictures for the "status/summary" comment.

== Dependencies

This section describes each services/modules that are going to be affected by this feature.

=== GitHub API

Our only supported VCS as of now.

=== GitLab API

TODO We are working on supporting GitLab and should investigate how to accomplish this there as well.

=== PostgreSQL

Currently, we do not store comment data in PostgreSQL. To implement any of the suggested solutions we would have to at least store:

. The Comment ID and its PR number.
. The status of a comment (e.g., active, superseded, minimized).
. Track the generation/version of a comment to maintain its modificatio history.

as for now we have the following tables tracking:

* `github_pull_requests`

[source,sql]
----
terrateam=> \d github_pull_requests
                   Table "public.github_pull_requests"
   Column    |           Type           | Collation | Nullable | Default 
-------------+--------------------------+-----------+----------+---------
 base_branch | text                     |           | not null | 
 base_sha    | text                     |           | not null | 
 branch      | text                     |           | not null | 
 pull_number | bigint                   |           | not null | 
 repository  | bigint                   |           | not null | 
 sha         | text                     |           | not null | 
 state       | text                     |           | not null | 
 merged_sha  | text                     |           |          | 
 merged_at   | timestamp with time zone |           |          | 
 title       | text                     |           |          | 
 username    | text                     |           |          | 
----

* `github_pull_requests_map`

[source,sql]
----
terrateam=> \d github_pull_requests_map
              Table "public.github_pull_requests_map"
    Column     |  Type  | Collation | Nullable |      Default      
---------------+--------+-----------+----------+-------------------
 repository_id | bigint |           | not null | 
 pull_number   | bigint |           | not null | 
 core_id       | uuid   |           | not null | gen_random_uuid()
----

=== Terrateam Configuration

. Given that our aim to make the most configurable IaC tool ever, we need to embed a new set of configurations and default values.
. Focus on making it per-directory so people can have freedom to apply different commenting rules.

== Proposals

=== Storage

First, we must have a way to:

. Store and link comments to Repos & Pull Requests
. Link existing comments to `work_manifests`
. Build a history of comment modification (for the anchor/summary comment)

==== First Proposal

This first proposal aims to use no extra extensions and leverages at least two tables that holds comment data.

TODO Add better comments to the source code.

[source,sql]
----
-- CREATING A SCHEMA SO WE CAN EASILY DROP THIS
-- DROP SCHEMA test_schame CASCADE
CREATE SCHEMA IF NOT EXISTS test_schema;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Custom Types
CREATE TYPE test_schema.github_comment_status AS ENUM (
    'active',
    'overwritten',
    'minimized'
);

CREATE TYPE test_schema.github_comment_type AS ENUM (
    'summary'
);

-- Tables
CREATE TABLE IF NOT EXISTS test_schema.github_comment(
    -- The original id github gave uses
    id BIGINT CONSTRAINT id_is_always_positive CHECK (id > 0) NOT NULL,
    --Commented to make testing this easier
    --pr_number BIGINT REFERENCES github_pull_requests (pull_number),
    --repository BIGINT REFERENCES github_pull_requests (repository),
    status test_schema.github_comment_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    --PRIMARY KEY (repository, pr_number, id)
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS test_schema.github_comment_history (
    id BIGINT REFERENCES test_schema.github_comment(id),
    status test_schema.github_comment_status NOT NULL,
    content TEXT CONSTRAINT content_length_upper_bound CHECK (
        LENGTH(content) <= 4096
    ) NOT NULL,
    content_digest TEXT GENERATED ALWAYS AS (encode(digest(content, 'sha256'), 'hex')) STORED,
    modified_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id, content_digest)
);

CREATE TABLE IF NOT EXISTS test_schema.github_comment_with_work_manifest(
    comment_id BIGINT REFERENCES test_schema.github_comment(id),
    work_manifest_id UUID REFERENCES work_manifests(id),
    PRIMARY KEY (comment_id)
);

-- Views
-- Main
CREATE OR REPLACE VIEW test_schema.github_comments_view AS 
SELECT 
    --gc.repository,
    --gc.pr_number,
    gc.id,
    gch.status,
    gch.content,
    ROW_NUMBER() OVER w AS version
FROM test_schema.github_comment gc
JOIN test_schema.github_comment_history gch ON gc.id = gch.id
WINDOW w AS (PARTITION BY gc.id ORDER BY gch.modified_at);

-- Functions & Triggers
CREATE OR REPLACE FUNCTION test_schema.upsert_github_comment() 
RETURNS trigger LANGUAGE plpgsql AS $$	
BEGIN	
  -- Upsert the main comment table
  INSERT INTO test_schema.github_comment (id, status)
  VALUES (NEW.id, NEW.status)
  ON CONFLICT (id)
  DO UPDATE 
    SET 
      status = EXCLUDED.status;
  
  -- Insert new version into the comment history
  INSERT INTO test_schema.github_comment_history (id, status, content)
  VALUES (NEW.id, NEW.status, NEW.content);
  
  RETURN NULL;
END $$;
  
CREATE OR REPLACE TRIGGER upsert_github_comment_trigger 
INSTEAD OF INSERT ON test_schema.github_comments_view
FOR EACH ROW EXECUTE FUNCTION test_schema.upsert_github_comment(); 

-- Indexes
-- Leave other indexes for later
--CREATE INDEX idx_github_pr_comments
--ON test_schema.github_comment USING BTREE(repository, pr_number)
--INCLUDE(id, status);

CREATE INDEX idx_github_pr_comment_modification_history
ON test_schema.github_comment_history USING BTREE(id)
INCLUDE(status, content);
----

Here's an example on how the updatable views can be leveraged to not expose the structure behind the internal tables:

[source,sql]
----
INSERT INTO test_schema.github_comments_view(id, status, content)
VALUES 
    (1, 'active', 'foo'),
    (1, 'overwritten', 'bar'),
    (1, 'minimized', 'foobar');
----

The `OCaml` codebase could focus only on inserting and reading from a view, the remaining machinery (and how it is supposed to work) can be kept consistent behind a view.

[source,sql]
----
terrateam=> SELECT * FROM test_schema.github_comments_view;
 id |   status    | content | version 
----+-------------+---------+---------
  1 | active      | foo     |       1
  1 | overwritten | bar     |       2
  1 | minimized   | foobar  |       3
(3 rows)
----

==== Second Proposal

This second proposal tries to leverage some of the SQL temporality features provider by some extensions, like https://github.com/xocolatl/periods[periods] or https://github.com/arkhipov/temporal_tables[temporal_tables]. This will work similarly to the previous approach, with the advantage that we can just leverage a single table.

=== Github Implementation

Github gives us two options:

* The GraphQL API supports https://docs.github.com/en/graphql/reference/mutations#minimizecomment[minimizeComment] and https://docs.github.com/en/graphql/reference/mutations#unminimizecomment[unminimizeComment], which can help our noise reduction effort by minimizing outdated comments.
* The REST API does not support these `minimize`/`unminimize` mutations, but allows for https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#update-an-issue-comment[updating comments], which can be used to maintain an "anchor" comment that is continuously updated with the latest status.

The following example is a proof-of-concept bash script on how to update a comment via the GitHub REST API.

[source,bash]
----
#!/usr/bin/env bash

GITHUB_TOKEN=$1
# org/repo
REPO=$2
# int
PR_NUMBER=$3
ORIGINAL_COMMENT="foo"
UPDATED_COMMENT="<details><summary>Generation 1</summary>$ORIGINAL_COMMENT</details>\n✅ LATEST COMMENT!"

response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -X POST \
    -d "{\"body\": \"$ORIGINAL_COMMENT\"}" \
    "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

comment_id=$(echo "$response" | jq -r '.id')

if [ "$comment_id" == "null" ]; then
  echo "ERROR: $response"
  exit 1
fi

echo "Comment ID: $comment_id"

sleep 5

echo "Updating comment..."
update_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -X PATCH \
    -d "{\"body\": \"$UPDATED_COMMENT\"}" \
    "https://api.github.com/repos/$REPO/issues/comments/$comment_id")

if echo "$update_response" | jq -e '.id' >/dev/null; then
  echo "Comment updated successfully."
else
  echo "ERROR: $update_response"
  exit 1
fi
----

NOTE: For context, we are currently using the REST API because there is a JSON schema for it and we create its OCaml module in a automated fashion. The GraphQL tooling is not the most awesome yet in OCaml, however it uses the same authentication token from the REST API, so we we can just write a function in `terrat_github` that does this one GraphQL call. 

=== Terrateam Configuration


== External References
