= Handling Old Comments
:authors: Marcos Benevides
:state: ideation
:labels: pull_requests
:source-highlighter: highlight.js
:toc:

== Status

Ideation.

== Goals

. Document how comments work as of now.
. Aggregate community suggestions.
. Describe possible implementations of https://github.com/terrateamio/terrateam/issues/116[terrateamio/terrateam#116].
. Discuss trade-offs of each alternative.

== Background

Currently, the Terrateam application posts comments in response to specific user events (triggered by commands such as `terrateam plan`, `terrateam apply`) on pull requests.

. Application comments are not currently tracked or stored in our systems; we rely solely on GitHub/GitLab as the source of truth.
. For multiple directories, each `terrateam plan` generates a distinct comment, leading to potential comment sprawl.
. There used to be a mechanism to deal with oversized comments, but it seems to be disabled now.
. Environments or batch builds produce multiple independent comments with no grouping, we have no mechanisms to group related comments together nor can we provide a consolidated summary.

=== Community Suggestions

The community has raised multiple suggestions around improving comment handling, mostly to reduce noise on pull requests. Some suggestions include:

. Introducing a _"status/summary"_ comment that acts as a consolidated view of all operations on a PR, reducing fragmentation of information and making it easier for reviewers to assess the state of infrastructure changes.
. Anchoring a single comment that is updated over time, rather than posting multiple new comments for each operation.

TODO Add pictures for the "status/summary" comment.

== Dependencies

This section describes each services/modules that are going to be affected by this feature.

=== GitHub API

Our only supported VCS as of now.

=== GitLab API

TODO We are working on supporting GitLab and should investigate how to accomplish this there as well.

=== PostgreSQL

Currently, we do not store comment data in PostgreSQL. To implement any of the suggested solutions we would have to at least store:

. The Comment ID and its PR number.
. The status of a comment (e.g., active, superseded, minimized).
. Track the generation/version of a comment to maintain its modificatio history.

as for now we have the following tables tracking:

. `github_pull_requests`

[source,sql]
----
terrateam=> \d github_pull_requests
                   Table "public.github_pull_requests"
   Column    |           Type           | Collation | Nullable | Default 
-------------+--------------------------+-----------+----------+---------
 base_branch | text                     |           | not null | 
 base_sha    | text                     |           | not null | 
 branch      | text                     |           | not null | 
 pull_number | bigint                   |           | not null | 
 repository  | bigint                   |           | not null | 
 sha         | text                     |           | not null | 
 state       | text                     |           | not null | 
 merged_sha  | text                     |           |          | 
 merged_at   | timestamp with time zone |           |          | 
 title       | text                     |           |          | 
 username    | text                     |           |          | 
----

. `github_pull_requests_map`

[source,sql]
----
terrateam=> \d github_pull_requests_map
              Table "public.github_pull_requests_map"
    Column     |  Type  | Collation | Nullable |      Default      
---------------+--------+-----------+----------+-------------------
 repository_id | bigint |           | not null | 
 pull_number   | bigint |           | not null | 
 core_id       | uuid   |           | not null | gen_random_uuid()
----

=== Terrateam Configuration

. Given that our aim to make the most configurable IaC tool ever, we need to embed a new set of configurations and default values.
. Focus on making it per-directory so people can have freedom to apply different commenting rules.

== Proposals

=== Storage

First, we must have a way to store and link comments.

[source,sql]
----
CREATE TYPE github_comment_status AS ENUM (
    'active',
    'superseded',
    'minimized'
);

CREATE TYPE github_comment_type AS ENUM (
    'summary',
);

-- Should we have our own ID as well?
CREATE TABLE IF NOT EXISTS github_comment(
    -- The original id github gave uses
    id BIGINT CONSTRAINT id_is_always_positive CHECK github_comment_id > 0
    pr_number BIGINT CONSTRAINT pr_num_is_always_positive CHECK github_comment_id > 0 NOT NULL
    version BIGINT CONSTRAINT version_is_always_positive CHECK github_comment_id > 0 NOT NULL
    content TEXT CONSTRAINT content_length_upper_bound CHECK (
        LENGTH(content) <= 4096
    ) NOT NULL,
    status github_comment_status NOT NULL,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (id, pr_number, version),
    PRIMARY KEY (github_comment_id)
);

CREATE UNIQUE INDEX pr_comments_idx
ON github_comment USING BTREE(pr_number)
-- Should we include the content as well?
INCLUDE(id, status, version);

-- To speed up queries that only look for 
-- active comments in a PR
CREATE UNIQUE INDEX pr_comments_active_idx
ON github_comment USING BTREE(pr_number)
WHERE status = 'active';
----

=== Github Implementation

Github gives us two options:

* The GraphQL API supports https://docs.github.com/en/graphql/reference/mutations#minimizecomment[minimizeComment] and https://docs.github.com/en/graphql/reference/mutations#unminimizecomment[unminimizeComment], which can help our noise reduction effort by minimizing outdated comments.
* The REST API does not support these `minimize`/`unminimize` mutations, but allows for https://docs.github.com/en/rest/issues/comments?apiVersion=2022-11-28#update-an-issue-comment[updating comments], which can be used to maintain an "anchor" comment that is continuously updated with the latest status.

The following example is a proof-of-concept bash script on how to update a comment via the GitHub REST API.

[source,bash]
----
#!/usr/bin/env bash

GITHUB_TOKEN=$1
# org/repo
REPO=$2
# int
PR_NUMBER=$3
ORIGINAL_COMMENT="foo"
UPDATED_COMMENT="<details><summary>Generation 1</summary>$ORIGINAL_COMMENT</details>\n✅ LATEST COMMENT!"

response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -X POST \
    -d "{\"body\": \"$ORIGINAL_COMMENT\"}" \
    "https://api.github.com/repos/$REPO/issues/$PR_NUMBER/comments")

comment_id=$(echo "$response" | jq -r '.id')

if [ "$comment_id" == "null" ]; then
  echo "ERROR: $response"
  exit 1
fi

echo "Comment ID: $comment_id"

sleep 5

echo "Updating comment..."
update_response=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
    -H "Accept: application/vnd.github+json" \
    -X PATCH \
    -d "{\"body\": \"$UPDATED_COMMENT\"}" \
    "https://api.github.com/repos/$REPO/issues/comments/$comment_id")

if echo "$update_response" | jq -e '.id' >/dev/null; then
  echo "Comment updated successfully."
else
  echo "ERROR: $update_response"
  exit 1
fi
----

NOTE: Using REST limits our ability to minimize old comments, as it's clunkier than GraphQL, but totally achievable.

=== Terrateam Configuration

== External References
