(* Generated by /tmp/gen_mql_tests.py from mql_parser_errors.messages.
   Each test feeds the example token trail of an error state into the
   parser and asserts the surfaced error message matches the message
   string written in mql_parser_errors.messages for that state. *)

let parse_kind kind input =
  match kind with
  | `Standalone_expr -> (
      match Mql.Ast.expr_of_string input with
      | Ok _ -> Error "parser unexpectedly succeeded"
      | Error (`Error (_, _, msg)) -> Ok msg)
  | `Start -> (
      match Mql.Ast.of_string input with
      | Ok _ -> Error "parser unexpectedly succeeded"
      | Error (`Error (_, _, msg)) -> Ok msg)

let is_integer s =
  s <> ""
  && CCString.for_all
       (function
         | '0' .. '9' -> true
         | _ -> false)
       s

let check_case ~state ~kind ~input ~expected _ =
  match parse_kind kind input with
  | Error err -> Oth.Assert.false_ (Printf.sprintf "state %d: %s (input=%S)" state err input)
  | Ok msg ->
      if msg <> expected then
        Oth.Assert.false_
          (Printf.sprintf "state %d: input=%S expected=%S got=%S" state input expected msg);
      if CCString.find ~sub:"YOUR SYNTAX ERROR" msg >= 0 then
        Oth.Assert.false_ (Printf.sprintf "state %d: placeholder leaked: %S" state msg);
      if is_integer msg then
        Oth.Assert.false_ (Printf.sprintf "state %d: bare integer message: %S" state msg)

let tests =
  [
    Oth.test
      ~name:"state_0"
      (check_case ~state:0 ~kind:`Standalone_expr ~input:"with" ~expected:"Expression expected.");
    Oth.test
      ~name:"state_4"
      (check_case
         ~state:4
         ~kind:`Standalone_expr
         ~input:"not with"
         ~expected:"Expression expected after 'not'.");
    Oth.test
      ~name:"state_5"
      (check_case
         ~state:5
         ~kind:`Standalone_expr
         ~input:"- with"
         ~expected:"Expression expected after unary '-'.");
    Oth.test
      ~name:"state_6"
      (check_case
         ~state:6
         ~kind:`Standalone_expr
         ~input:"(with"
         ~expected:"Expression or tuple expected after '('.");
    Oth.test
      ~name:"state_8"
      (check_case
         ~state:8
         ~kind:`Standalone_expr
         ~input:"foo with"
         ~expected:
           "Expected an operator, '(' for function call, or end of expression after identifier.");
    Oth.test
      ~name:"state_9"
      (check_case
         ~state:9
         ~kind:`Standalone_expr
         ~input:"foo (with"
         ~expected:"Expression or ')' expected in function call argument list.");
    Oth.test
      ~name:"state_13"
      (check_case
         ~state:13
         ~kind:`Standalone_expr
         ~input:"exists with"
         ~expected:"Expected '(' after 'exists'.");
    Oth.test
      ~name:"state_14"
      (check_case
         ~state:14
         ~kind:`Standalone_expr
         ~input:"exists (where"
         ~expected:"Query expected inside 'exists ('.");
    Oth.test
      ~name:"state_15"
      (check_case
         ~state:15
         ~kind:`Start
         ~input:"with with"
         ~expected:"Identifier expected for CTE name after 'with'.");
    Oth.test
      ~name:"state_16"
      (check_case
         ~state:16
         ~kind:`Start
         ~input:"with foo with"
         ~expected:"Expected 'as' after CTE name.");
    Oth.test
      ~name:"state_17"
      (check_case
         ~state:17
         ~kind:`Start
         ~input:"with foo as with"
         ~expected:"Expected '(' or 'materialized' after 'as' in CTE definition.");
    Oth.test
      ~name:"state_18"
      (check_case
         ~state:18
         ~kind:`Start
         ~input:"with foo as materialized with"
         ~expected:"Expected '(' after 'materialized'.");
    Oth.test
      ~name:"state_19"
      (check_case
         ~state:19
         ~kind:`Start
         ~input:"with foo as materialized (where"
         ~expected:"Query expected inside materialized CTE.");
    Oth.test
      ~name:"state_20"
      (check_case
         ~state:20
         ~kind:`Start
         ~input:"select with"
         ~expected:"Select list expected after 'select'.");
    Oth.test
      ~name:"state_22"
      (check_case
         ~state:22
         ~kind:`Standalone_expr
         ~input:"count with"
         ~expected:"Expected '(' after 'count'.");
    Oth.test
      ~name:"state_23"
      (check_case
         ~state:23
         ~kind:`Standalone_expr
         ~input:"count (with"
         ~expected:"Expected '*' inside 'count(...)'.");
    Oth.test
      ~name:"state_24"
      (check_case
         ~state:24
         ~kind:`Standalone_expr
         ~input:"count (* with"
         ~expected:"Expected ')' to close 'count(*)'.");
    Oth.test
      ~name:"state_26"
      (check_case
         ~state:26
         ~kind:`Start
         ~input:"select false as foo with"
         ~expected:"Expected ',' or 'from' after select column.");
    Oth.test
      ~name:"state_27"
      (check_case
         ~state:27
         ~kind:`Start
         ~input:"select false, with"
         ~expected:"Column expression expected after ',' in select list.");
    Oth.test
      ~name:"state_28"
      (check_case
         ~state:28
         ~kind:`Start
         ~input:"select false where"
         ~expected:"Expected an operator, 'as', ',' or 'from' after column expression.");
    Oth.test
      ~name:"state_29"
      (check_case
         ~state:29
         ~kind:`Standalone_expr
         ~input:"false * with"
         ~expected:"Expression expected after '*'.");
    Oth.test
      ~name:"state_30"
      (check_case
         ~state:30
         ~kind:`Standalone_expr
         ~input:"false * false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_31"
      (check_case
         ~state:31
         ~kind:`Standalone_expr
         ~input:"false [with"
         ~expected:"Expression expected inside '[...]'.");
    Oth.test
      ~name:"state_32"
      (check_case
         ~state:32
         ~kind:`Standalone_expr
         ~input:"false [false where"
         ~expected:"Expected ']' to close index expression.");
    Oth.test
      ~name:"state_34"
      (check_case
         ~state:34
         ~kind:`Standalone_expr
         ~input:"false + with"
         ~expected:"Expression expected after '+'.");
    Oth.test
      ~name:"state_35"
      (check_case
         ~state:35
         ~kind:`Standalone_expr
         ~input:"false + false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_36"
      (check_case
         ~state:36
         ~kind:`Standalone_expr
         ~input:"false-> with"
         ~expected:"Expression expected after '->'.");
    Oth.test
      ~name:"state_37"
      (check_case
         ~state:37
         ~kind:`Standalone_expr
         ~input:"false-> false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_38"
      (check_case
         ~state:38
         ~kind:`Standalone_expr
         ~input:"false:: with"
         ~expected:"Identifier (type name) expected after '::'.");
    Oth.test
      ~name:"state_40"
      (check_case
         ~state:40
         ~kind:`Standalone_expr
         ~input:"false.with"
         ~expected:"Identifier expected after '.'.");
    Oth.test
      ~name:"state_42"
      (check_case
         ~state:42
         ~kind:`Standalone_expr
         ~input:"false->> with"
         ~expected:"Expression expected after '->>'.");
    Oth.test
      ~name:"state_43"
      (check_case
         ~state:43
         ~kind:`Standalone_expr
         ~input:"false->> false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_44"
      (check_case
         ~state:44
         ~kind:`Standalone_expr
         ~input:"false #>> with"
         ~expected:"String literal expected after '#>>'.");
    Oth.test
      ~name:"state_46"
      (check_case
         ~state:46
         ~kind:`Standalone_expr
         ~input:"false || with"
         ~expected:"Expression expected after '||'.");
    Oth.test
      ~name:"state_47"
      (check_case
         ~state:47
         ~kind:`Standalone_expr
         ~input:"false || false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_48"
      (check_case
         ~state:48
         ~kind:`Standalone_expr
         ~input:"false / with"
         ~expected:"Expression expected after '/'.");
    Oth.test
      ~name:"state_49"
      (check_case
         ~state:49
         ~kind:`Standalone_expr
         ~input:"false / false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_50"
      (check_case
         ~state:50
         ~kind:`Standalone_expr
         ~input:"false or with"
         ~expected:"Expression expected after 'or'.");
    Oth.test
      ~name:"state_51"
      (check_case
         ~state:51
         ~kind:`Standalone_expr
         ~input:"false or false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_52"
      (check_case
         ~state:52
         ~kind:`Standalone_expr
         ~input:"false <> with"
         ~expected:"Expression expected after '<>'.");
    Oth.test
      ~name:"state_53"
      (check_case
         ~state:53
         ~kind:`Standalone_expr
         ~input:"false <> false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_54"
      (check_case
         ~state:54
         ~kind:`Standalone_expr
         ~input:"false - with"
         ~expected:"Expression expected after '-'.");
    Oth.test
      ~name:"state_55"
      (check_case
         ~state:55
         ~kind:`Standalone_expr
         ~input:"false - false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_56"
      (check_case
         ~state:56
         ~kind:`Standalone_expr
         ~input:"false not with"
         ~expected:"Expected 'like' or 'ilike' after 'not'.");
    Oth.test
      ~name:"state_57"
      (check_case
         ~state:57
         ~kind:`Standalone_expr
         ~input:"false not like with"
         ~expected:"Expression expected after 'not like'.");
    Oth.test
      ~name:"state_58"
      (check_case
         ~state:58
         ~kind:`Standalone_expr
         ~input:"false not like false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_59"
      (check_case
         ~state:59
         ~kind:`Standalone_expr
         ~input:"false not ilike with"
         ~expected:"Expression expected after 'not ilike'.");
    Oth.test
      ~name:"state_60"
      (check_case
         ~state:60
         ~kind:`Standalone_expr
         ~input:"false not ilike false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_61"
      (check_case
         ~state:61
         ~kind:`Standalone_expr
         ~input:"false <= with"
         ~expected:"Expression expected after '<='.");
    Oth.test
      ~name:"state_62"
      (check_case
         ~state:62
         ~kind:`Standalone_expr
         ~input:"false <= false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_63"
      (check_case
         ~state:63
         ~kind:`Standalone_expr
         ~input:"false < with"
         ~expected:"Expression expected after '<'.");
    Oth.test
      ~name:"state_64"
      (check_case
         ~state:64
         ~kind:`Standalone_expr
         ~input:"false < false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_65"
      (check_case
         ~state:65
         ~kind:`Standalone_expr
         ~input:"false like with"
         ~expected:"Expression expected after 'like'.");
    Oth.test
      ~name:"state_66"
      (check_case
         ~state:66
         ~kind:`Standalone_expr
         ~input:"false like false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_67"
      (check_case
         ~state:67
         ~kind:`Standalone_expr
         ~input:"false@> with"
         ~expected:"Expression expected after '@>'.");
    Oth.test
      ~name:"state_68"
      (check_case
         ~state:68
         ~kind:`Standalone_expr
         ~input:"false@> false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_69"
      (check_case
         ~state:69
         ~kind:`Standalone_expr
         ~input:"false is not distinct from with"
         ~expected:"Expression expected after 'is not distinct from'.");
    Oth.test
      ~name:"state_70"
      (check_case
         ~state:70
         ~kind:`Standalone_expr
         ~input:"false is not distinct from false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_71"
      (check_case
         ~state:71
         ~kind:`Standalone_expr
         ~input:"false is not with"
         ~expected:"Expression expected after 'is not'.");
    Oth.test
      ~name:"state_72"
      (check_case
         ~state:72
         ~kind:`Standalone_expr
         ~input:"false is not false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_73"
      (check_case
         ~state:73
         ~kind:`Standalone_expr
         ~input:"false is distinct from with"
         ~expected:"Expression expected after 'is distinct from'.");
    Oth.test
      ~name:"state_74"
      (check_case
         ~state:74
         ~kind:`Standalone_expr
         ~input:"false is distinct from false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_75"
      (check_case
         ~state:75
         ~kind:`Standalone_expr
         ~input:"false is with"
         ~expected:"Expression expected after 'is'.");
    Oth.test
      ~name:"state_76"
      (check_case
         ~state:76
         ~kind:`Standalone_expr
         ~input:"false is false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_77"
      (check_case
         ~state:77
         ~kind:`Standalone_expr
         ~input:"false in with"
         ~expected:"Expected '(' after 'in'.");
    Oth.test
      ~name:"state_78"
      (check_case
         ~state:78
         ~kind:`Standalone_expr
         ~input:"false in (where"
         ~expected:"Expression list or subquery expected inside 'in (...)'.");
    Oth.test
      ~name:"state_79"
      (check_case
         ~state:79
         ~kind:`Standalone_expr
         ~input:"false in ((where"
         ~expected:"Expression, tuple, or query expected after '('.");
    Oth.test
      ~name:"state_83"
      (check_case
         ~state:83
         ~kind:`Standalone_expr
         ~input:"(false, false, with"
         ~expected:"Expression expected after ',' in tuple.");
    Oth.test
      ~name:"state_84"
      (check_case
         ~state:84
         ~kind:`Standalone_expr
         ~input:"(false, false, false where"
         ~expected:"Expected an operator, ',' or ')' after expression in tuple.");
    Oth.test
      ~name:"state_85"
      (check_case
         ~state:85
         ~kind:`Standalone_expr
         ~input:"false ilike with"
         ~expected:"Expression expected after 'ilike'.");
    Oth.test
      ~name:"state_86"
      (check_case
         ~state:86
         ~kind:`Standalone_expr
         ~input:"false ilike false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_87"
      (check_case
         ~state:87
         ~kind:`Standalone_expr
         ~input:"false >= with"
         ~expected:"Expression expected after '>='.");
    Oth.test
      ~name:"state_88"
      (check_case
         ~state:88
         ~kind:`Standalone_expr
         ~input:"false >= false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_89"
      (check_case
         ~state:89
         ~kind:`Standalone_expr
         ~input:"false > with"
         ~expected:"Expression expected after '>'.");
    Oth.test
      ~name:"state_90"
      (check_case
         ~state:90
         ~kind:`Standalone_expr
         ~input:"false > false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_91"
      (check_case
         ~state:91
         ~kind:`Standalone_expr
         ~input:"false = with"
         ~expected:"Expression expected after '='.");
    Oth.test
      ~name:"state_92"
      (check_case
         ~state:92
         ~kind:`Standalone_expr
         ~input:"false = false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_93"
      (check_case
         ~state:93
         ~kind:`Standalone_expr
         ~input:"false and with"
         ~expected:"Expression expected after 'and'.");
    Oth.test
      ~name:"state_94"
      (check_case
         ~state:94
         ~kind:`Standalone_expr
         ~input:"false and false with"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_96"
      (check_case
         ~state:96
         ~kind:`Start
         ~input:"(select false from foo) with"
         ~expected:"Expected 'union', 'order by', 'limit', ')' or end of query.");
    Oth.test
      ~name:"state_97"
      (check_case
         ~state:97
         ~kind:`Start
         ~input:"select false from foo union with"
         ~expected:"Query expected after 'union'.");
    Oth.test
      ~name:"state_98"
      (check_case ~state:98 ~kind:`Start ~input:"(where" ~expected:"Query expected inside '('.");
    Oth.test
      ~name:"state_99"
      (check_case
         ~state:99
         ~kind:`Start
         ~input:"(select false from foo"
         ~expected:"Expected ')' to close parenthesized query.");
    Oth.test
      ~name:"state_101"
      (check_case
         ~state:101
         ~kind:`Start
         ~input:"select false from foo union all with"
         ~expected:"Query expected after 'union all'.");
    Oth.test
      ~name:"state_104"
      (check_case
         ~state:104
         ~kind:`Start
         ~input:"select false from foo order with"
         ~expected:"Expected 'by' after 'order'.");
    Oth.test
      ~name:"state_105"
      (check_case
         ~state:105
         ~kind:`Start
         ~input:"select false from foo order by with"
         ~expected:"Expression expected after 'order by'.");
    Oth.test
      ~name:"state_106"
      (check_case
         ~state:106
         ~kind:`Start
         ~input:"select false from foo order by false asc with"
         ~expected:"Expected ',', 'limit', ')' or end of query after order-by expression.");
    Oth.test
      ~name:"state_107"
      (check_case
         ~state:107
         ~kind:`Start
         ~input:"select false from foo limit with"
         ~expected:"Integer expected after 'limit'.");
    Oth.test
      ~name:"state_109"
      (check_case
         ~state:109
         ~kind:`Start
         ~input:"select false from foo order by false, with"
         ~expected:"Expression expected after ',' in order-by list.");
    Oth.test
      ~name:"state_111"
      (check_case
         ~state:111
         ~kind:`Start
         ~input:"select false from foo order by false where"
         ~expected:
           "Expected an operator, 'asc', 'desc', ',', 'limit', ')' or end of query after order-by \
            expression.");
    Oth.test
      ~name:"state_118"
      (check_case
         ~state:118
         ~kind:`Standalone_expr
         ~input:"(false where"
         ~expected:"Expected ')' to close parenthesized expression.");
    Oth.test
      ~name:"state_120"
      (check_case
         ~state:120
         ~kind:`Standalone_expr
         ~input:"(false, with"
         ~expected:"Expression expected after ',' in tuple.");
    Oth.test
      ~name:"state_121"
      (check_case
         ~state:121
         ~kind:`Standalone_expr
         ~input:"(false, false where"
         ~expected:"Expected ',' or ')' in tuple.");
    Oth.test
      ~name:"state_122"
      (check_case
         ~state:122
         ~kind:`Standalone_expr
         ~input:"false in (select false from foo"
         ~expected:"Expected ')' to close 'in (...)' subquery.");
    Oth.test
      ~name:"state_126"
      (check_case
         ~state:126
         ~kind:`Standalone_expr
         ~input:"false in (false, with"
         ~expected:"Expression expected after ',' in IN list.");
    Oth.test
      ~name:"state_127"
      (check_case
         ~state:127
         ~kind:`Standalone_expr
         ~input:"false in (false, false where"
         ~expected:"Expected ',' or ')' in IN list.");
    Oth.test
      ~name:"state_128"
      (check_case
         ~state:128
         ~kind:`Standalone_expr
         ~input:"false in (false where"
         ~expected:"Expected an operator, ',' or ')' after expression in IN list.");
    Oth.test
      ~name:"state_129"
      (check_case
         ~state:129
         ~kind:`Start
         ~input:"select false as with"
         ~expected:"Identifier expected after 'as' for column alias.");
    Oth.test
      ~name:"state_132"
      (check_case
         ~state:132
         ~kind:`Start
         ~input:"select * with"
         ~expected:"Expected 'from' after select list.");
    Oth.test
      ~name:"state_133"
      (check_case
         ~state:133
         ~kind:`Start
         ~input:"select false from with"
         ~expected:"Table reference or 'unnest(...)' expected after 'from'.");
    Oth.test
      ~name:"state_134"
      (check_case
         ~state:134
         ~kind:`Start
         ~input:"select false from unnest with"
         ~expected:"Expected '(' after 'unnest'.");
    Oth.test
      ~name:"state_135"
      (check_case
         ~state:135
         ~kind:`Start
         ~input:"select false from unnest (with"
         ~expected:"Expression expected inside 'unnest(...)'.");
    Oth.test
      ~name:"state_136"
      (check_case
         ~state:136
         ~kind:`Start
         ~input:"select false from unnest (false where"
         ~expected:"Expected an operator or ')' after expression in 'unnest(...)'.");
    Oth.test
      ~name:"state_137"
      (check_case
         ~state:137
         ~kind:`Start
         ~input:"select false from unnest (false) with"
         ~expected:"Expected 'as' after 'unnest(...)'.");
    Oth.test
      ~name:"state_138"
      (check_case
         ~state:138
         ~kind:`Start
         ~input:"select false from unnest (false) as with"
         ~expected:"Identifier expected for 'unnest(...)' alias.");
    Oth.test
      ~name:"state_140"
      (check_case
         ~state:140
         ~kind:`Start
         ~input:"select false from foo with"
         ~expected:
           "Expected 'as', ',', a join keyword, 'where', 'group by', 'order by', 'limit', 'union', \
            ')' or end of query after table name.");
    Oth.test
      ~name:"state_141"
      (check_case
         ~state:141
         ~kind:`Start
         ~input:"select false from foo as with"
         ~expected:"Identifier expected for table alias after 'as'.");
    Oth.test
      ~name:"state_143"
      (check_case
         ~state:143
         ~kind:`Start
         ~input:"select false from foo on"
         ~expected:
           "Expected ',', a join keyword, 'where', 'group by', 'order by', 'limit', 'union', ')' \
            or end of query after table list.");
    Oth.test
      ~name:"state_144"
      (check_case
         ~state:144
         ~kind:`Start
         ~input:"select false from foo where with"
         ~expected:"Expression expected after 'where'.");
    Oth.test
      ~name:"state_145"
      (check_case
         ~state:145
         ~kind:`Start
         ~input:"select false from foo where false where"
         ~expected:
           "Expected an operator, 'group by', 'order by', 'limit', 'union', ')' or end of query \
            after WHERE expression.");
    Oth.test
      ~name:"state_146"
      (check_case
         ~state:146
         ~kind:`Start
         ~input:"select false from foo group with"
         ~expected:"Expected 'by' after 'group'.");
    Oth.test
      ~name:"state_147"
      (check_case
         ~state:147
         ~kind:`Start
         ~input:"select false from foo group by with"
         ~expected:"Expression expected after 'group by'.");
    Oth.test
      ~name:"state_149"
      (check_case
         ~state:149
         ~kind:`Start
         ~input:"select false from foo group by false having with"
         ~expected:"Expression expected after 'having'.");
    Oth.test
      ~name:"state_150"
      (check_case
         ~state:150
         ~kind:`Start
         ~input:"select false from foo group by false having false where"
         ~expected:
           "Expected an operator, 'order by', 'limit', 'union', ')' or end of query after HAVING \
            expression.");
    Oth.test
      ~name:"state_151"
      (check_case
         ~state:151
         ~kind:`Start
         ~input:"select false from foo group by false, with"
         ~expected:"Expression expected after ',' in group-by list.");
    Oth.test
      ~name:"state_152"
      (check_case
         ~state:152
         ~kind:`Start
         ~input:"select false from foo group by false, false where"
         ~expected:
           "Expected an operator, ',', 'having', 'order by', 'limit', 'union', ')' or end of query \
            after group-by expression.");
    Oth.test
      ~name:"state_153"
      (check_case
         ~state:153
         ~kind:`Start
         ~input:"select false from foo group by false where"
         ~expected:
           "Expected an operator, ',', 'having', 'order by', 'limit', 'union', ')' or end of query \
            after group-by expression.");
    Oth.test
      ~name:"state_155"
      (check_case
         ~state:155
         ~kind:`Start
         ~input:"select false from foo right with"
         ~expected:"Expected 'join' after 'right'.");
    Oth.test
      ~name:"state_156"
      (check_case
         ~state:156
         ~kind:`Start
         ~input:"select false from foo right join with"
         ~expected:"Table reference expected after 'right join'.");
    Oth.test
      ~name:"state_157"
      (check_case
         ~state:157
         ~kind:`Start
         ~input:"select false from foo right join foo where"
         ~expected:"Expected 'on' after join table.");
    Oth.test
      ~name:"state_158"
      (check_case
         ~state:158
         ~kind:`Start
         ~input:"select false from foo right join foo on with"
         ~expected:"Join condition expression expected after 'on'.");
    Oth.test
      ~name:"state_159"
      (check_case
         ~state:159
         ~kind:`Start
         ~input:"select false from foo right join foo on false]"
         ~expected:
           "Expected an operator, another join, 'where', 'group by', 'order by', 'limit', 'union', \
            ')' or end of query after join condition.");
    Oth.test
      ~name:"state_160"
      (check_case
         ~state:160
         ~kind:`Start
         ~input:"select false from foo left with"
         ~expected:"Expected 'join' after 'left'.");
    Oth.test
      ~name:"state_161"
      (check_case
         ~state:161
         ~kind:`Start
         ~input:"select false from foo left join with"
         ~expected:"Table reference expected after 'left join'.");
    Oth.test
      ~name:"state_162"
      (check_case
         ~state:162
         ~kind:`Start
         ~input:"select false from foo left join foo where"
         ~expected:"Expected 'on' after join table.");
    Oth.test
      ~name:"state_163"
      (check_case
         ~state:163
         ~kind:`Start
         ~input:"select false from foo left join foo on with"
         ~expected:"Join condition expression expected after 'on'.");
    Oth.test
      ~name:"state_164"
      (check_case
         ~state:164
         ~kind:`Start
         ~input:"select false from foo left join foo on false]"
         ~expected:
           "Expected an operator, another join, 'where', 'group by', 'order by', 'limit', 'union', \
            ')' or end of query after join condition.");
    Oth.test
      ~name:"state_165"
      (check_case
         ~state:165
         ~kind:`Start
         ~input:"select false from foo inner with"
         ~expected:"Expected 'join' after 'inner'.");
    Oth.test
      ~name:"state_166"
      (check_case
         ~state:166
         ~kind:`Start
         ~input:"select false from foo inner join with"
         ~expected:"Table reference expected after 'inner join'.");
    Oth.test
      ~name:"state_167"
      (check_case
         ~state:167
         ~kind:`Start
         ~input:"select false from foo inner join foo where"
         ~expected:"Expected 'on' after join table.");
    Oth.test
      ~name:"state_168"
      (check_case
         ~state:168
         ~kind:`Start
         ~input:"select false from foo inner join foo on with"
         ~expected:"Join condition expression expected after 'on'.");
    Oth.test
      ~name:"state_169"
      (check_case
         ~state:169
         ~kind:`Start
         ~input:"select false from foo inner join foo on false]"
         ~expected:
           "Expected an operator, another join, 'where', 'group by', 'order by', 'limit', 'union', \
            ')' or end of query after join condition.");
    Oth.test
      ~name:"state_170"
      (check_case
         ~state:170
         ~kind:`Start
         ~input:"select false from foo, with"
         ~expected:"Table reference or 'unnest(...)' expected after ',' in FROM clause.");
    Oth.test
      ~name:"state_182"
      (check_case
         ~state:182
         ~kind:`Start
         ~input:"with foo as materialized (select false from foo"
         ~expected:"Expected ')' to close materialized CTE.");
    Oth.test
      ~name:"state_184"
      (check_case
         ~state:184
         ~kind:`Start
         ~input:"with foo as (where"
         ~expected:"Query expected inside CTE.");
    Oth.test
      ~name:"state_185"
      (check_case
         ~state:185
         ~kind:`Start
         ~input:"with foo as (select false from foo"
         ~expected:"Expected ')' to close CTE.");
    Oth.test
      ~name:"state_187"
      (check_case
         ~state:187
         ~kind:`Start
         ~input:"with foo as (select false from foo) where"
         ~expected:"Expected ',' or a query after CTE definitions.");
    Oth.test
      ~name:"state_188"
      (check_case
         ~state:188
         ~kind:`Start
         ~input:"with foo as (select false from foo), with"
         ~expected:"CTE name (identifier) expected after ',' in WITH clause.");
    Oth.test
      ~name:"state_192"
      (check_case
         ~state:192
         ~kind:`Standalone_expr
         ~input:"exists (select false from foo"
         ~expected:"Expected ')' to close 'exists (...)'.");
    Oth.test
      ~name:"state_196"
      (check_case
         ~state:196
         ~kind:`Standalone_expr
         ~input:"foo (false, with"
         ~expected:"Expression expected after ',' in function argument list.");
    Oth.test
      ~name:"state_197"
      (check_case
         ~state:197
         ~kind:`Standalone_expr
         ~input:"foo (false, false where"
         ~expected:"Expected an operator, ',' or ')' after function argument.");
    Oth.test
      ~name:"state_198"
      (check_case
         ~state:198
         ~kind:`Standalone_expr
         ~input:"foo (false where"
         ~expected:"Expected an operator, ',' or ')' after function argument.");
    Oth.test
      ~name:"state_199"
      (check_case
         ~state:199
         ~kind:`Standalone_expr
         ~input:"- false with"
         ~expected:"Expected an operator or end of expression after negated expression.");
    Oth.test
      ~name:"state_200"
      (check_case
         ~state:200
         ~kind:`Standalone_expr
         ~input:"not false with"
         ~expected:"Expected an operator or end of expression after 'not' expression.");
    Oth.test
      ~name:"state_202"
      (check_case
         ~state:202
         ~kind:`Standalone_expr
         ~input:"false where"
         ~expected:"Expected an operator or end of expression.");
    Oth.test
      ~name:"state_204"
      (check_case
         ~state:204
         ~kind:`Start
         ~input:"where"
         ~expected:"Expected 'select' or 'with' at start of query.");
    Oth.test
      ~name:"state_206"
      (check_case
         ~state:206
         ~kind:`Start
         ~input:"select false from foo)"
         ~expected:"Expected end of input after query.");
  ]

let () =
  Random.self_init ();
  Oth.run (Oth.parallel tests)
