module Actions_billing_usage = Githubc2_components_actions_billing_usage
module Actions_cache_list = Githubc2_components_actions_cache_list
module Actions_cache_usage_by_repository = Githubc2_components_actions_cache_usage_by_repository
module Actions_cache_usage_org_enterprise = Githubc2_components_actions_cache_usage_org_enterprise

module Actions_can_approve_pull_request_reviews =
  Githubc2_components_actions_can_approve_pull_request_reviews

module Actions_default_workflow_permissions =
  Githubc2_components_actions_default_workflow_permissions

module Actions_enabled = Githubc2_components_actions_enabled

module Actions_get_default_workflow_permissions =
  Githubc2_components_actions_get_default_workflow_permissions

module Actions_hosted_runner = Githubc2_components_actions_hosted_runner
module Actions_hosted_runner_image = Githubc2_components_actions_hosted_runner_image
module Actions_hosted_runner_limits = Githubc2_components_actions_hosted_runner_limits
module Actions_hosted_runner_machine_spec = Githubc2_components_actions_hosted_runner_machine_spec
module Actions_organization_permissions = Githubc2_components_actions_organization_permissions
module Actions_public_key = Githubc2_components_actions_public_key
module Actions_repository_permissions = Githubc2_components_actions_repository_permissions
module Actions_secret = Githubc2_components_actions_secret

module Actions_set_default_workflow_permissions =
  Githubc2_components_actions_set_default_workflow_permissions

module Actions_variable = Githubc2_components_actions_variable

module Actions_workflow_access_to_repository =
  Githubc2_components_actions_workflow_access_to_repository

module Activity = Githubc2_components_activity
module Actor = Githubc2_components_actor
module Added_to_project_issue_event = Githubc2_components_added_to_project_issue_event
module Alert_auto_dismissed_at = Githubc2_components_alert_auto_dismissed_at
module Alert_created_at = Githubc2_components_alert_created_at
module Alert_dismissed_at = Githubc2_components_alert_dismissed_at
module Alert_fixed_at = Githubc2_components_alert_fixed_at
module Alert_html_url = Githubc2_components_alert_html_url
module Alert_instances_url = Githubc2_components_alert_instances_url
module Alert_number = Githubc2_components_alert_number
module Alert_updated_at = Githubc2_components_alert_updated_at
module Alert_url = Githubc2_components_alert_url
module Allowed_actions = Githubc2_components_allowed_actions
module Api_insights_route_stats = Githubc2_components_api_insights_route_stats
module Api_insights_subject_stats = Githubc2_components_api_insights_subject_stats
module Api_insights_summary_stats = Githubc2_components_api_insights_summary_stats
module Api_insights_time_stats = Githubc2_components_api_insights_time_stats
module Api_insights_user_stats = Githubc2_components_api_insights_user_stats
module Api_overview = Githubc2_components_api_overview
module App_permissions = Githubc2_components_app_permissions
module Artifact = Githubc2_components_artifact
module Assigned_issue_event = Githubc2_components_assigned_issue_event
module Authentication_token = Githubc2_components_authentication_token
module Author_association = Githubc2_components_author_association
module Authorization = Githubc2_components_authorization
module Auto_merge = Githubc2_components_auto_merge
module Autolink = Githubc2_components_autolink
module Base_gist = Githubc2_components_base_gist
module Basic_error = Githubc2_components_basic_error
module Billing_usage_report = Githubc2_components_billing_usage_report
module Blob = Githubc2_components_blob
module Branch_protection = Githubc2_components_branch_protection
module Branch_restriction_policy = Githubc2_components_branch_restriction_policy
module Branch_short = Githubc2_components_branch_short
module Branch_with_protection = Githubc2_components_branch_with_protection
module Campaign_state = Githubc2_components_campaign_state
module Campaign_summary = Githubc2_components_campaign_summary
module Check_annotation = Githubc2_components_check_annotation
module Check_automated_security_fixes = Githubc2_components_check_automated_security_fixes
module Check_run = Githubc2_components_check_run
module Check_run_with_simple_check_suite = Githubc2_components_check_run_with_simple_check_suite
module Check_suite = Githubc2_components_check_suite
module Check_suite_preference = Githubc2_components_check_suite_preference
module Classroom = Githubc2_components_classroom
module Classroom_accepted_assignment = Githubc2_components_classroom_accepted_assignment
module Classroom_assignment = Githubc2_components_classroom_assignment
module Classroom_assignment_grade = Githubc2_components_classroom_assignment_grade
module Clone_traffic = Githubc2_components_clone_traffic
module Code_frequency_stat = Githubc2_components_code_frequency_stat
module Code_of_conduct = Githubc2_components_code_of_conduct
module Code_of_conduct_simple = Githubc2_components_code_of_conduct_simple
module Code_scanning_alert = Githubc2_components_code_scanning_alert
module Code_scanning_alert_classification = Githubc2_components_code_scanning_alert_classification
module Code_scanning_alert_create_request = Githubc2_components_code_scanning_alert_create_request

module Code_scanning_alert_dismissed_comment =
  Githubc2_components_code_scanning_alert_dismissed_comment

module Code_scanning_alert_dismissed_reason =
  Githubc2_components_code_scanning_alert_dismissed_reason

module Code_scanning_alert_environment = Githubc2_components_code_scanning_alert_environment
module Code_scanning_alert_instance = Githubc2_components_code_scanning_alert_instance
module Code_scanning_alert_items = Githubc2_components_code_scanning_alert_items
module Code_scanning_alert_location = Githubc2_components_code_scanning_alert_location
module Code_scanning_alert_rule = Githubc2_components_code_scanning_alert_rule
module Code_scanning_alert_rule_summary = Githubc2_components_code_scanning_alert_rule_summary
module Code_scanning_alert_set_state = Githubc2_components_code_scanning_alert_set_state
module Code_scanning_alert_severity = Githubc2_components_code_scanning_alert_severity
module Code_scanning_alert_state = Githubc2_components_code_scanning_alert_state
module Code_scanning_alert_state_query = Githubc2_components_code_scanning_alert_state_query
module Code_scanning_analysis = Githubc2_components_code_scanning_analysis
module Code_scanning_analysis_analysis_key = Githubc2_components_code_scanning_analysis_analysis_key
module Code_scanning_analysis_category = Githubc2_components_code_scanning_analysis_category
module Code_scanning_analysis_commit_sha = Githubc2_components_code_scanning_analysis_commit_sha
module Code_scanning_analysis_created_at = Githubc2_components_code_scanning_analysis_created_at
module Code_scanning_analysis_deletion = Githubc2_components_code_scanning_analysis_deletion
module Code_scanning_analysis_environment = Githubc2_components_code_scanning_analysis_environment
module Code_scanning_analysis_sarif_file = Githubc2_components_code_scanning_analysis_sarif_file
module Code_scanning_analysis_sarif_id = Githubc2_components_code_scanning_analysis_sarif_id
module Code_scanning_analysis_tool = Githubc2_components_code_scanning_analysis_tool
module Code_scanning_analysis_tool_guid = Githubc2_components_code_scanning_analysis_tool_guid
module Code_scanning_analysis_tool_name = Githubc2_components_code_scanning_analysis_tool_name
module Code_scanning_analysis_tool_version = Githubc2_components_code_scanning_analysis_tool_version
module Code_scanning_analysis_url = Githubc2_components_code_scanning_analysis_url
module Code_scanning_autofix = Githubc2_components_code_scanning_autofix
module Code_scanning_autofix_commits = Githubc2_components_code_scanning_autofix_commits

module Code_scanning_autofix_commits_response =
  Githubc2_components_code_scanning_autofix_commits_response

module Code_scanning_autofix_description = Githubc2_components_code_scanning_autofix_description
module Code_scanning_autofix_started_at = Githubc2_components_code_scanning_autofix_started_at
module Code_scanning_autofix_status = Githubc2_components_code_scanning_autofix_status
module Code_scanning_codeql_database = Githubc2_components_code_scanning_codeql_database
module Code_scanning_default_setup = Githubc2_components_code_scanning_default_setup
module Code_scanning_default_setup_options = Githubc2_components_code_scanning_default_setup_options
module Code_scanning_default_setup_update = Githubc2_components_code_scanning_default_setup_update

module Code_scanning_default_setup_update_response =
  Githubc2_components_code_scanning_default_setup_update_response

module Code_scanning_organization_alert_items =
  Githubc2_components_code_scanning_organization_alert_items

module Code_scanning_ref = Githubc2_components_code_scanning_ref
module Code_scanning_ref_full = Githubc2_components_code_scanning_ref_full
module Code_scanning_sarifs_receipt = Githubc2_components_code_scanning_sarifs_receipt
module Code_scanning_sarifs_status = Githubc2_components_code_scanning_sarifs_status
module Code_scanning_variant_analysis = Githubc2_components_code_scanning_variant_analysis

module Code_scanning_variant_analysis_language =
  Githubc2_components_code_scanning_variant_analysis_language

module Code_scanning_variant_analysis_repo_task =
  Githubc2_components_code_scanning_variant_analysis_repo_task

module Code_scanning_variant_analysis_repository =
  Githubc2_components_code_scanning_variant_analysis_repository

module Code_scanning_variant_analysis_skipped_repo_group =
  Githubc2_components_code_scanning_variant_analysis_skipped_repo_group

module Code_scanning_variant_analysis_status =
  Githubc2_components_code_scanning_variant_analysis_status

module Code_search_result_item = Githubc2_components_code_search_result_item
module Code_security_configuration = Githubc2_components_code_security_configuration

module Code_security_configuration_for_repository =
  Githubc2_components_code_security_configuration_for_repository

module Code_security_configuration_repositories =
  Githubc2_components_code_security_configuration_repositories

module Code_security_default_configurations =
  Githubc2_components_code_security_default_configurations

module Codeowners_errors = Githubc2_components_codeowners_errors
module Codespace = Githubc2_components_codespace
module Codespace_export_details = Githubc2_components_codespace_export_details
module Codespace_machine = Githubc2_components_codespace_machine
module Codespace_with_full_repository = Githubc2_components_codespace_with_full_repository
module Codespaces_org_secret = Githubc2_components_codespaces_org_secret

module Codespaces_permissions_check_for_devcontainer =
  Githubc2_components_codespaces_permissions_check_for_devcontainer

module Codespaces_public_key = Githubc2_components_codespaces_public_key
module Codespaces_secret = Githubc2_components_codespaces_secret
module Codespaces_user_public_key = Githubc2_components_codespaces_user_public_key
module Collaborator = Githubc2_components_collaborator
module Combined_billing_usage = Githubc2_components_combined_billing_usage
module Combined_commit_status = Githubc2_components_combined_commit_status
module Commit = Githubc2_components_commit
module Commit_activity = Githubc2_components_commit_activity
module Commit_comment = Githubc2_components_commit_comment
module Commit_comparison = Githubc2_components_commit_comparison
module Commit_search_result_item = Githubc2_components_commit_search_result_item
module Community_profile = Githubc2_components_community_profile
module Content_directory = Githubc2_components_content_directory
module Content_file = Githubc2_components_content_file
module Content_submodule = Githubc2_components_content_submodule
module Content_symlink = Githubc2_components_content_symlink
module Content_traffic = Githubc2_components_content_traffic
module Content_tree = Githubc2_components_content_tree
module Contributor = Githubc2_components_contributor
module Contributor_activity = Githubc2_components_contributor_activity
module Converted_note_to_issue_issue_event = Githubc2_components_converted_note_to_issue_issue_event
module Copilot_dotcom_chat = Githubc2_components_copilot_dotcom_chat
module Copilot_dotcom_pull_requests = Githubc2_components_copilot_dotcom_pull_requests
module Copilot_ide_chat = Githubc2_components_copilot_ide_chat
module Copilot_ide_code_completions = Githubc2_components_copilot_ide_code_completions
module Copilot_organization_details = Githubc2_components_copilot_organization_details
module Copilot_organization_seat_breakdown = Githubc2_components_copilot_organization_seat_breakdown
module Copilot_seat_details = Githubc2_components_copilot_seat_details
module Copilot_usage_metrics_day = Githubc2_components_copilot_usage_metrics_day
module Custom_deployment_rule_app = Githubc2_components_custom_deployment_rule_app
module Custom_property = Githubc2_components_custom_property
module Custom_property_set_payload = Githubc2_components_custom_property_set_payload
module Custom_property_value = Githubc2_components_custom_property_value
module Cvss_severities = Githubc2_components_cvss_severities
module Demilestoned_issue_event = Githubc2_components_demilestoned_issue_event
module Dependabot_alert = Githubc2_components_dependabot_alert
module Dependabot_alert_package = Githubc2_components_dependabot_alert_package
module Dependabot_alert_security_advisory = Githubc2_components_dependabot_alert_security_advisory

module Dependabot_alert_security_vulnerability =
  Githubc2_components_dependabot_alert_security_vulnerability

module Dependabot_alert_with_repository = Githubc2_components_dependabot_alert_with_repository
module Dependabot_public_key = Githubc2_components_dependabot_public_key
module Dependabot_secret = Githubc2_components_dependabot_secret
module Dependency = Githubc2_components_dependency
module Dependency_graph_diff = Githubc2_components_dependency_graph_diff
module Dependency_graph_spdx_sbom = Githubc2_components_dependency_graph_spdx_sbom
module Deploy_key = Githubc2_components_deploy_key
module Deployment = Githubc2_components_deployment
module Deployment_branch_policy = Githubc2_components_deployment_branch_policy

module Deployment_branch_policy_name_pattern =
  Githubc2_components_deployment_branch_policy_name_pattern

module Deployment_branch_policy_name_pattern_with_type =
  Githubc2_components_deployment_branch_policy_name_pattern_with_type

module Deployment_branch_policy_settings = Githubc2_components_deployment_branch_policy_settings
module Deployment_protection_rule = Githubc2_components_deployment_protection_rule
module Deployment_reviewer_type = Githubc2_components_deployment_reviewer_type
module Deployment_simple = Githubc2_components_deployment_simple
module Deployment_status = Githubc2_components_deployment_status
module Diff_entry = Githubc2_components_diff_entry
module Discussion = Githubc2_components_discussion
module Email = Githubc2_components_email
module Empty_object = Githubc2_components_empty_object
module Enabled_repositories = Githubc2_components_enabled_repositories
module Enterprise = Githubc2_components_enterprise
module Enterprise_team = Githubc2_components_enterprise_team
module Enterprise_webhooks = Githubc2_components_enterprise_webhooks
module Environment = Githubc2_components_environment
module Environment_approvals = Githubc2_components_environment_approvals
module Event = Githubc2_components_event
module Feed = Githubc2_components_feed
module File_commit = Githubc2_components_file_commit
module Full_repository = Githubc2_components_full_repository
module Gist_comment = Githubc2_components_gist_comment
module Gist_commit = Githubc2_components_gist_commit
module Gist_history = Githubc2_components_gist_history
module Gist_simple = Githubc2_components_gist_simple
module Git_commit = Githubc2_components_git_commit
module Git_ref = Githubc2_components_git_ref
module Git_tag = Githubc2_components_git_tag
module Git_tree = Githubc2_components_git_tree
module Gitignore_template = Githubc2_components_gitignore_template
module Global_advisory = Githubc2_components_global_advisory
module Gpg_key = Githubc2_components_gpg_key
module Hook = Githubc2_components_hook
module Hook_delivery = Githubc2_components_hook_delivery
module Hook_delivery_item = Githubc2_components_hook_delivery_item
module Hook_response = Githubc2_components_hook_response
module Hovercard = Githubc2_components_hovercard
module Import = Githubc2_components_import
module Installation = Githubc2_components_installation
module Installation_token = Githubc2_components_installation_token
module Integration = Githubc2_components_integration
module Integration_installation_request = Githubc2_components_integration_installation_request
module Interaction_expiry = Githubc2_components_interaction_expiry
module Interaction_group = Githubc2_components_interaction_group
module Interaction_limit = Githubc2_components_interaction_limit
module Interaction_limit_response = Githubc2_components_interaction_limit_response
module Issue = Githubc2_components_issue
module Issue_comment = Githubc2_components_issue_comment
module Issue_event = Githubc2_components_issue_event
module Issue_event_dismissed_review = Githubc2_components_issue_event_dismissed_review
module Issue_event_for_issue = Githubc2_components_issue_event_for_issue
module Issue_event_label = Githubc2_components_issue_event_label
module Issue_event_milestone = Githubc2_components_issue_event_milestone
module Issue_event_project_card = Githubc2_components_issue_event_project_card
module Issue_event_rename = Githubc2_components_issue_event_rename
module Issue_search_result_item = Githubc2_components_issue_search_result_item
module Issue_type = Githubc2_components_issue_type
module Job = Githubc2_components_job
module Key = Githubc2_components_key
module Key_simple = Githubc2_components_key_simple
module Label = Githubc2_components_label
module Label_search_result_item = Githubc2_components_label_search_result_item
module Labeled_issue_event = Githubc2_components_labeled_issue_event
module Language = Githubc2_components_language
module License = Githubc2_components_license
module License_content = Githubc2_components_license_content
module License_simple = Githubc2_components_license_simple
module Link = Githubc2_components_link
module Link_with_type = Githubc2_components_link_with_type
module Locked_issue_event = Githubc2_components_locked_issue_event
module Manifest = Githubc2_components_manifest
module Marketplace_account = Githubc2_components_marketplace_account
module Marketplace_listing_plan = Githubc2_components_marketplace_listing_plan
module Marketplace_purchase = Githubc2_components_marketplace_purchase
module Merge_group = Githubc2_components_merge_group
module Merged_upstream = Githubc2_components_merged_upstream
module Metadata = Githubc2_components_metadata
module Migration = Githubc2_components_migration
module Milestone = Githubc2_components_milestone
module Milestoned_issue_event = Githubc2_components_milestoned_issue_event
module Minimal_repository = Githubc2_components_minimal_repository
module Moved_column_in_project_issue_event = Githubc2_components_moved_column_in_project_issue_event
module Network_configuration = Githubc2_components_network_configuration
module Network_settings = Githubc2_components_network_settings

module Nullable_actions_hosted_runner_pool_image =
  Githubc2_components_nullable_actions_hosted_runner_pool_image

module Nullable_alert_updated_at = Githubc2_components_nullable_alert_updated_at
module Nullable_code_of_conduct_simple = Githubc2_components_nullable_code_of_conduct_simple
module Nullable_codespace_machine = Githubc2_components_nullable_codespace_machine
module Nullable_collaborator = Githubc2_components_nullable_collaborator
module Nullable_community_health_file = Githubc2_components_nullable_community_health_file
module Nullable_git_user = Githubc2_components_nullable_git_user
module Nullable_integration = Githubc2_components_nullable_integration
module Nullable_issue = Githubc2_components_nullable_issue
module Nullable_license_simple = Githubc2_components_nullable_license_simple
module Nullable_milestone = Githubc2_components_nullable_milestone
module Nullable_minimal_repository = Githubc2_components_nullable_minimal_repository
module Nullable_organization_simple = Githubc2_components_nullable_organization_simple
module Nullable_repository = Githubc2_components_nullable_repository
module Nullable_repository_webhooks = Githubc2_components_nullable_repository_webhooks
module Nullable_scoped_installation = Githubc2_components_nullable_scoped_installation
module Nullable_simple_commit = Githubc2_components_nullable_simple_commit
module Nullable_simple_user = Githubc2_components_nullable_simple_user
module Nullable_team_simple = Githubc2_components_nullable_team_simple
module Oidc_custom_sub = Githubc2_components_oidc_custom_sub
module Oidc_custom_sub_repo = Githubc2_components_oidc_custom_sub_repo
module Org_hook = Githubc2_components_org_hook
module Org_membership = Githubc2_components_org_membership
module Org_private_registry_configuration = Githubc2_components_org_private_registry_configuration

module Org_private_registry_configuration_with_selected_repositories =
  Githubc2_components_org_private_registry_configuration_with_selected_repositories

module Org_repo_custom_property_values = Githubc2_components_org_repo_custom_property_values
module Org_ruleset_conditions = Githubc2_components_org_ruleset_conditions
module Organization_actions_secret = Githubc2_components_organization_actions_secret
module Organization_actions_variable = Githubc2_components_organization_actions_variable
module Organization_create_issue_type = Githubc2_components_organization_create_issue_type
module Organization_dependabot_secret = Githubc2_components_organization_dependabot_secret
module Organization_full = Githubc2_components_organization_full
module Organization_invitation = Githubc2_components_organization_invitation

module Organization_programmatic_access_grant =
  Githubc2_components_organization_programmatic_access_grant

module Organization_programmatic_access_grant_request =
  Githubc2_components_organization_programmatic_access_grant_request

module Organization_role = Githubc2_components_organization_role
module Organization_secret_scanning_alert = Githubc2_components_organization_secret_scanning_alert
module Organization_simple = Githubc2_components_organization_simple
module Organization_simple_webhooks = Githubc2_components_organization_simple_webhooks
module Organization_update_issue_type = Githubc2_components_organization_update_issue_type
module Package = Githubc2_components_package
module Package_version = Githubc2_components_package_version
module Packages_billing_usage = Githubc2_components_packages_billing_usage
module Page = Githubc2_components_page
module Page_build = Githubc2_components_page_build
module Page_build_status = Githubc2_components_page_build_status
module Page_deployment = Githubc2_components_page_deployment
module Pages_deployment_status = Githubc2_components_pages_deployment_status
module Pages_health_check = Githubc2_components_pages_health_check
module Pages_https_certificate = Githubc2_components_pages_https_certificate
module Pages_source_hash = Githubc2_components_pages_source_hash
module Participation_stats = Githubc2_components_participation_stats
module Pending_deployment = Githubc2_components_pending_deployment
module Personal_access_token_request = Githubc2_components_personal_access_token_request
module Porter_author = Githubc2_components_porter_author
module Porter_large_file = Githubc2_components_porter_large_file
module Prevent_self_review = Githubc2_components_prevent_self_review
module Private_user = Githubc2_components_private_user
module Private_vulnerability_report_create = Githubc2_components_private_vulnerability_report_create
module Project = Githubc2_components_project
module Project_card = Githubc2_components_project_card
module Project_collaborator_permission = Githubc2_components_project_collaborator_permission
module Project_column = Githubc2_components_project_column
module Projects_v2 = Githubc2_components_projects_v2
module Projects_v2_item = Githubc2_components_projects_v2_item
module Projects_v2_item_content_type = Githubc2_components_projects_v2_item_content_type
module Projects_v2_iteration_setting = Githubc2_components_projects_v2_iteration_setting
module Projects_v2_single_select_option = Githubc2_components_projects_v2_single_select_option
module Projects_v2_status_update = Githubc2_components_projects_v2_status_update
module Protected_branch = Githubc2_components_protected_branch
module Protected_branch_admin_enforced = Githubc2_components_protected_branch_admin_enforced

module Protected_branch_pull_request_review =
  Githubc2_components_protected_branch_pull_request_review

module Protected_branch_required_status_check =
  Githubc2_components_protected_branch_required_status_check

module Public_ip = Githubc2_components_public_ip
module Public_user = Githubc2_components_public_user
module Pull_request = Githubc2_components_pull_request
module Pull_request_merge_result = Githubc2_components_pull_request_merge_result
module Pull_request_minimal = Githubc2_components_pull_request_minimal
module Pull_request_review = Githubc2_components_pull_request_review
module Pull_request_review_comment = Githubc2_components_pull_request_review_comment
module Pull_request_review_request = Githubc2_components_pull_request_review_request
module Pull_request_simple = Githubc2_components_pull_request_simple
module Pull_request_webhook = Githubc2_components_pull_request_webhook
module Rate_limit = Githubc2_components_rate_limit
module Rate_limit_overview = Githubc2_components_rate_limit_overview
module Reaction = Githubc2_components_reaction
module Reaction_rollup = Githubc2_components_reaction_rollup
module Referenced_workflow = Githubc2_components_referenced_workflow
module Referrer_traffic = Githubc2_components_referrer_traffic
module Release = Githubc2_components_release
module Release_asset = Githubc2_components_release_asset
module Release_notes_content = Githubc2_components_release_notes_content
module Removed_from_project_issue_event = Githubc2_components_removed_from_project_issue_event
module Renamed_issue_event = Githubc2_components_renamed_issue_event
module Repo_codespaces_secret = Githubc2_components_repo_codespaces_secret
module Repo_search_result_item = Githubc2_components_repo_search_result_item
module Repository = Githubc2_components_repository
module Repository_advisory = Githubc2_components_repository_advisory
module Repository_advisory_create = Githubc2_components_repository_advisory_create
module Repository_advisory_credit = Githubc2_components_repository_advisory_credit
module Repository_advisory_update = Githubc2_components_repository_advisory_update
module Repository_advisory_vulnerability = Githubc2_components_repository_advisory_vulnerability
module Repository_collaborator_permission = Githubc2_components_repository_collaborator_permission
module Repository_invitation = Githubc2_components_repository_invitation
module Repository_rule = Githubc2_components_repository_rule
module Repository_rule_branch_name_pattern = Githubc2_components_repository_rule_branch_name_pattern
module Repository_rule_code_scanning = Githubc2_components_repository_rule_code_scanning

module Repository_rule_commit_author_email_pattern =
  Githubc2_components_repository_rule_commit_author_email_pattern

module Repository_rule_commit_message_pattern =
  Githubc2_components_repository_rule_commit_message_pattern

module Repository_rule_committer_email_pattern =
  Githubc2_components_repository_rule_committer_email_pattern

module Repository_rule_creation = Githubc2_components_repository_rule_creation
module Repository_rule_deletion = Githubc2_components_repository_rule_deletion
module Repository_rule_detailed = Githubc2_components_repository_rule_detailed
module Repository_rule_enforcement = Githubc2_components_repository_rule_enforcement

module Repository_rule_file_extension_restriction =
  Githubc2_components_repository_rule_file_extension_restriction

module Repository_rule_file_path_restriction =
  Githubc2_components_repository_rule_file_path_restriction

module Repository_rule_max_file_path_length =
  Githubc2_components_repository_rule_max_file_path_length

module Repository_rule_max_file_size = Githubc2_components_repository_rule_max_file_size
module Repository_rule_merge_queue = Githubc2_components_repository_rule_merge_queue
module Repository_rule_non_fast_forward = Githubc2_components_repository_rule_non_fast_forward

module Repository_rule_params_code_scanning_tool =
  Githubc2_components_repository_rule_params_code_scanning_tool

module Repository_rule_params_required_reviewer_configuration =
  Githubc2_components_repository_rule_params_required_reviewer_configuration

module Repository_rule_params_restricted_commits =
  Githubc2_components_repository_rule_params_restricted_commits

module Repository_rule_params_reviewer = Githubc2_components_repository_rule_params_reviewer

module Repository_rule_params_status_check_configuration =
  Githubc2_components_repository_rule_params_status_check_configuration

module Repository_rule_params_workflow_file_reference =
  Githubc2_components_repository_rule_params_workflow_file_reference

module Repository_rule_pull_request = Githubc2_components_repository_rule_pull_request

module Repository_rule_required_deployments =
  Githubc2_components_repository_rule_required_deployments

module Repository_rule_required_linear_history =
  Githubc2_components_repository_rule_required_linear_history

module Repository_rule_required_signatures = Githubc2_components_repository_rule_required_signatures

module Repository_rule_required_status_checks =
  Githubc2_components_repository_rule_required_status_checks

module Repository_rule_ruleset_info = Githubc2_components_repository_rule_ruleset_info
module Repository_rule_tag_name_pattern = Githubc2_components_repository_rule_tag_name_pattern
module Repository_rule_update = Githubc2_components_repository_rule_update
module Repository_rule_violation_error = Githubc2_components_repository_rule_violation_error
module Repository_rule_workflows = Githubc2_components_repository_rule_workflows
module Repository_ruleset = Githubc2_components_repository_ruleset
module Repository_ruleset_bypass_actor = Githubc2_components_repository_ruleset_bypass_actor
module Repository_ruleset_conditions = Githubc2_components_repository_ruleset_conditions

module Repository_ruleset_conditions_repository_id_target =
  Githubc2_components_repository_ruleset_conditions_repository_id_target

module Repository_ruleset_conditions_repository_name_target =
  Githubc2_components_repository_ruleset_conditions_repository_name_target

module Repository_ruleset_conditions_repository_property_spec =
  Githubc2_components_repository_ruleset_conditions_repository_property_spec

module Repository_ruleset_conditions_repository_property_target =
  Githubc2_components_repository_ruleset_conditions_repository_property_target

module Repository_subscription = Githubc2_components_repository_subscription
module Repository_webhooks = Githubc2_components_repository_webhooks
module Review_comment = Githubc2_components_review_comment

module Review_custom_gates_comment_required =
  Githubc2_components_review_custom_gates_comment_required

module Review_custom_gates_state_required = Githubc2_components_review_custom_gates_state_required
module Review_dismissed_issue_event = Githubc2_components_review_dismissed_issue_event
module Review_request_removed_issue_event = Githubc2_components_review_request_removed_issue_event
module Review_requested_issue_event = Githubc2_components_review_requested_issue_event
module Root = Githubc2_components_root
module Rule_suite = Githubc2_components_rule_suite
module Rule_suites = Githubc2_components_rule_suites
module Ruleset_version = Githubc2_components_ruleset_version
module Ruleset_version_with_state = Githubc2_components_ruleset_version_with_state
module Runner = Githubc2_components_runner
module Runner_application = Githubc2_components_runner_application
module Runner_groups_org = Githubc2_components_runner_groups_org
module Runner_label = Githubc2_components_runner_label
module Scim_error = Githubc2_components_scim_error
module Search_result_text_matches = Githubc2_components_search_result_text_matches
module Secret_scanning_alert = Githubc2_components_secret_scanning_alert
module Secret_scanning_alert_resolution = Githubc2_components_secret_scanning_alert_resolution

module Secret_scanning_alert_resolution_comment =
  Githubc2_components_secret_scanning_alert_resolution_comment

module Secret_scanning_alert_resolution_webhook =
  Githubc2_components_secret_scanning_alert_resolution_webhook

module Secret_scanning_alert_state = Githubc2_components_secret_scanning_alert_state
module Secret_scanning_alert_webhook = Githubc2_components_secret_scanning_alert_webhook
module Secret_scanning_location = Githubc2_components_secret_scanning_location
module Secret_scanning_location_commit = Githubc2_components_secret_scanning_location_commit

module Secret_scanning_location_discussion_body =
  Githubc2_components_secret_scanning_location_discussion_body

module Secret_scanning_location_discussion_comment =
  Githubc2_components_secret_scanning_location_discussion_comment

module Secret_scanning_location_discussion_title =
  Githubc2_components_secret_scanning_location_discussion_title

module Secret_scanning_location_issue_body = Githubc2_components_secret_scanning_location_issue_body

module Secret_scanning_location_issue_comment =
  Githubc2_components_secret_scanning_location_issue_comment

module Secret_scanning_location_issue_title =
  Githubc2_components_secret_scanning_location_issue_title

module Secret_scanning_location_pull_request_body =
  Githubc2_components_secret_scanning_location_pull_request_body

module Secret_scanning_location_pull_request_comment =
  Githubc2_components_secret_scanning_location_pull_request_comment

module Secret_scanning_location_pull_request_review =
  Githubc2_components_secret_scanning_location_pull_request_review

module Secret_scanning_location_pull_request_review_comment =
  Githubc2_components_secret_scanning_location_pull_request_review_comment

module Secret_scanning_location_pull_request_title =
  Githubc2_components_secret_scanning_location_pull_request_title

module Secret_scanning_location_wiki_commit =
  Githubc2_components_secret_scanning_location_wiki_commit

module Secret_scanning_push_protection_bypass =
  Githubc2_components_secret_scanning_push_protection_bypass

module Secret_scanning_push_protection_bypass_placeholder_id =
  Githubc2_components_secret_scanning_push_protection_bypass_placeholder_id

module Secret_scanning_push_protection_bypass_reason =
  Githubc2_components_secret_scanning_push_protection_bypass_reason

module Secret_scanning_scan = Githubc2_components_secret_scanning_scan
module Secret_scanning_scan_history = Githubc2_components_secret_scanning_scan_history
module Security_advisory_credit_types = Githubc2_components_security_advisory_credit_types
module Security_advisory_ecosystems = Githubc2_components_security_advisory_ecosystems
module Security_advisory_epss = Githubc2_components_security_advisory_epss
module Security_and_analysis = Githubc2_components_security_and_analysis
module Selected_actions = Githubc2_components_selected_actions
module Selected_actions_url = Githubc2_components_selected_actions_url
module Short_blob = Githubc2_components_short_blob
module Short_branch = Githubc2_components_short_branch
module Simple_check_suite = Githubc2_components_simple_check_suite
module Simple_classroom = Githubc2_components_simple_classroom
module Simple_classroom_assignment = Githubc2_components_simple_classroom_assignment
module Simple_classroom_organization = Githubc2_components_simple_classroom_organization
module Simple_classroom_repository = Githubc2_components_simple_classroom_repository
module Simple_classroom_user = Githubc2_components_simple_classroom_user
module Simple_commit = Githubc2_components_simple_commit
module Simple_commit_status = Githubc2_components_simple_commit_status
module Simple_installation = Githubc2_components_simple_installation
module Simple_repository = Githubc2_components_simple_repository
module Simple_user = Githubc2_components_simple_user
module Snapshot = Githubc2_components_snapshot
module Social_account = Githubc2_components_social_account
module Ssh_signing_key = Githubc2_components_ssh_signing_key
module Stargazer = Githubc2_components_stargazer
module Starred_repository = Githubc2_components_starred_repository
module State_change_issue_event = Githubc2_components_state_change_issue_event
module Status = Githubc2_components_status
module Status_check_policy = Githubc2_components_status_check_policy
module Sub_issues_summary = Githubc2_components_sub_issues_summary
module Tag = Githubc2_components_tag
module Tag_protection = Githubc2_components_tag_protection
module Team = Githubc2_components_team
module Team_discussion = Githubc2_components_team_discussion
module Team_discussion_comment = Githubc2_components_team_discussion_comment
module Team_full = Githubc2_components_team_full
module Team_membership = Githubc2_components_team_membership
module Team_organization = Githubc2_components_team_organization
module Team_project = Githubc2_components_team_project
module Team_repository = Githubc2_components_team_repository
module Team_role_assignment = Githubc2_components_team_role_assignment
module Team_simple = Githubc2_components_team_simple
module Thread = Githubc2_components_thread
module Thread_subscription = Githubc2_components_thread_subscription
module Timeline_assigned_issue_event = Githubc2_components_timeline_assigned_issue_event
module Timeline_comment_event = Githubc2_components_timeline_comment_event
module Timeline_commit_commented_event = Githubc2_components_timeline_commit_commented_event
module Timeline_committed_event = Githubc2_components_timeline_committed_event
module Timeline_cross_referenced_event = Githubc2_components_timeline_cross_referenced_event
module Timeline_issue_events = Githubc2_components_timeline_issue_events
module Timeline_line_commented_event = Githubc2_components_timeline_line_commented_event
module Timeline_reviewed_event = Githubc2_components_timeline_reviewed_event
module Timeline_unassigned_issue_event = Githubc2_components_timeline_unassigned_issue_event
module Topic = Githubc2_components_topic
module Topic_search_result_item = Githubc2_components_topic_search_result_item
module Traffic = Githubc2_components_traffic
module Unassigned_issue_event = Githubc2_components_unassigned_issue_event
module Unlabeled_issue_event = Githubc2_components_unlabeled_issue_event
module User_marketplace_purchase = Githubc2_components_user_marketplace_purchase
module User_role_assignment = Githubc2_components_user_role_assignment
module User_search_result_item = Githubc2_components_user_search_result_item
module Validation_error = Githubc2_components_validation_error
module Validation_error_simple = Githubc2_components_validation_error_simple
module Verification = Githubc2_components_verification
module View_traffic = Githubc2_components_view_traffic
module Vulnerability = Githubc2_components_vulnerability
module Wait_timer = Githubc2_components_wait_timer

module Webhook_branch_protection_configuration_disabled =
  Githubc2_components_webhook_branch_protection_configuration_disabled

module Webhook_branch_protection_configuration_enabled =
  Githubc2_components_webhook_branch_protection_configuration_enabled

module Webhook_branch_protection_rule_created =
  Githubc2_components_webhook_branch_protection_rule_created

module Webhook_branch_protection_rule_deleted =
  Githubc2_components_webhook_branch_protection_rule_deleted

module Webhook_branch_protection_rule_edited =
  Githubc2_components_webhook_branch_protection_rule_edited

module Webhook_check_run_completed = Githubc2_components_webhook_check_run_completed

module Webhook_check_run_completed_form_encoded =
  Githubc2_components_webhook_check_run_completed_form_encoded

module Webhook_check_run_created = Githubc2_components_webhook_check_run_created

module Webhook_check_run_created_form_encoded =
  Githubc2_components_webhook_check_run_created_form_encoded

module Webhook_check_run_requested_action = Githubc2_components_webhook_check_run_requested_action

module Webhook_check_run_requested_action_form_encoded =
  Githubc2_components_webhook_check_run_requested_action_form_encoded

module Webhook_check_run_rerequested = Githubc2_components_webhook_check_run_rerequested

module Webhook_check_run_rerequested_form_encoded =
  Githubc2_components_webhook_check_run_rerequested_form_encoded

module Webhook_check_suite_completed = Githubc2_components_webhook_check_suite_completed
module Webhook_check_suite_requested = Githubc2_components_webhook_check_suite_requested
module Webhook_check_suite_rerequested = Githubc2_components_webhook_check_suite_rerequested

module Webhook_code_scanning_alert_appeared_in_branch =
  Githubc2_components_webhook_code_scanning_alert_appeared_in_branch

module Webhook_code_scanning_alert_closed_by_user =
  Githubc2_components_webhook_code_scanning_alert_closed_by_user

module Webhook_code_scanning_alert_created = Githubc2_components_webhook_code_scanning_alert_created
module Webhook_code_scanning_alert_fixed = Githubc2_components_webhook_code_scanning_alert_fixed

module Webhook_code_scanning_alert_reopened =
  Githubc2_components_webhook_code_scanning_alert_reopened

module Webhook_code_scanning_alert_reopened_by_user =
  Githubc2_components_webhook_code_scanning_alert_reopened_by_user

module Webhook_commit_comment_created = Githubc2_components_webhook_commit_comment_created
module Webhook_config = Githubc2_components_webhook_config
module Webhook_config_content_type = Githubc2_components_webhook_config_content_type
module Webhook_config_insecure_ssl = Githubc2_components_webhook_config_insecure_ssl
module Webhook_config_secret = Githubc2_components_webhook_config_secret
module Webhook_config_url = Githubc2_components_webhook_config_url
module Webhook_create = Githubc2_components_webhook_create
module Webhook_custom_property_created = Githubc2_components_webhook_custom_property_created
module Webhook_custom_property_deleted = Githubc2_components_webhook_custom_property_deleted

module Webhook_custom_property_promoted_to_enterprise =
  Githubc2_components_webhook_custom_property_promoted_to_enterprise

module Webhook_custom_property_updated = Githubc2_components_webhook_custom_property_updated

module Webhook_custom_property_values_updated =
  Githubc2_components_webhook_custom_property_values_updated

module Webhook_delete = Githubc2_components_webhook_delete

module Webhook_dependabot_alert_auto_dismissed =
  Githubc2_components_webhook_dependabot_alert_auto_dismissed

module Webhook_dependabot_alert_auto_reopened =
  Githubc2_components_webhook_dependabot_alert_auto_reopened

module Webhook_dependabot_alert_created = Githubc2_components_webhook_dependabot_alert_created
module Webhook_dependabot_alert_dismissed = Githubc2_components_webhook_dependabot_alert_dismissed
module Webhook_dependabot_alert_fixed = Githubc2_components_webhook_dependabot_alert_fixed

module Webhook_dependabot_alert_reintroduced =
  Githubc2_components_webhook_dependabot_alert_reintroduced

module Webhook_dependabot_alert_reopened = Githubc2_components_webhook_dependabot_alert_reopened
module Webhook_deploy_key_created = Githubc2_components_webhook_deploy_key_created
module Webhook_deploy_key_deleted = Githubc2_components_webhook_deploy_key_deleted
module Webhook_deployment_created = Githubc2_components_webhook_deployment_created

module Webhook_deployment_protection_rule_requested =
  Githubc2_components_webhook_deployment_protection_rule_requested

module Webhook_deployment_review_approved = Githubc2_components_webhook_deployment_review_approved
module Webhook_deployment_review_rejected = Githubc2_components_webhook_deployment_review_rejected
module Webhook_deployment_review_requested = Githubc2_components_webhook_deployment_review_requested
module Webhook_deployment_status_created = Githubc2_components_webhook_deployment_status_created
module Webhook_discussion_answered = Githubc2_components_webhook_discussion_answered
module Webhook_discussion_category_changed = Githubc2_components_webhook_discussion_category_changed
module Webhook_discussion_closed = Githubc2_components_webhook_discussion_closed
module Webhook_discussion_comment_created = Githubc2_components_webhook_discussion_comment_created
module Webhook_discussion_comment_deleted = Githubc2_components_webhook_discussion_comment_deleted
module Webhook_discussion_comment_edited = Githubc2_components_webhook_discussion_comment_edited
module Webhook_discussion_created = Githubc2_components_webhook_discussion_created
module Webhook_discussion_deleted = Githubc2_components_webhook_discussion_deleted
module Webhook_discussion_edited = Githubc2_components_webhook_discussion_edited
module Webhook_discussion_labeled = Githubc2_components_webhook_discussion_labeled
module Webhook_discussion_locked = Githubc2_components_webhook_discussion_locked
module Webhook_discussion_pinned = Githubc2_components_webhook_discussion_pinned
module Webhook_discussion_reopened = Githubc2_components_webhook_discussion_reopened
module Webhook_discussion_transferred = Githubc2_components_webhook_discussion_transferred
module Webhook_discussion_unanswered = Githubc2_components_webhook_discussion_unanswered
module Webhook_discussion_unlabeled = Githubc2_components_webhook_discussion_unlabeled
module Webhook_discussion_unlocked = Githubc2_components_webhook_discussion_unlocked
module Webhook_discussion_unpinned = Githubc2_components_webhook_discussion_unpinned
module Webhook_fork = Githubc2_components_webhook_fork

module Webhook_github_app_authorization_revoked =
  Githubc2_components_webhook_github_app_authorization_revoked

module Webhook_gollum = Githubc2_components_webhook_gollum
module Webhook_installation_created = Githubc2_components_webhook_installation_created
module Webhook_installation_deleted = Githubc2_components_webhook_installation_deleted

module Webhook_installation_new_permissions_accepted =
  Githubc2_components_webhook_installation_new_permissions_accepted

module Webhook_installation_repositories_added =
  Githubc2_components_webhook_installation_repositories_added

module Webhook_installation_repositories_removed =
  Githubc2_components_webhook_installation_repositories_removed

module Webhook_installation_suspend = Githubc2_components_webhook_installation_suspend
module Webhook_installation_target_renamed = Githubc2_components_webhook_installation_target_renamed
module Webhook_installation_unsuspend = Githubc2_components_webhook_installation_unsuspend
module Webhook_issue_comment_created = Githubc2_components_webhook_issue_comment_created
module Webhook_issue_comment_deleted = Githubc2_components_webhook_issue_comment_deleted
module Webhook_issue_comment_edited = Githubc2_components_webhook_issue_comment_edited
module Webhook_issues_assigned = Githubc2_components_webhook_issues_assigned
module Webhook_issues_closed = Githubc2_components_webhook_issues_closed
module Webhook_issues_deleted = Githubc2_components_webhook_issues_deleted
module Webhook_issues_demilestoned = Githubc2_components_webhook_issues_demilestoned
module Webhook_issues_edited = Githubc2_components_webhook_issues_edited
module Webhook_issues_labeled = Githubc2_components_webhook_issues_labeled
module Webhook_issues_locked = Githubc2_components_webhook_issues_locked
module Webhook_issues_milestoned = Githubc2_components_webhook_issues_milestoned
module Webhook_issues_opened = Githubc2_components_webhook_issues_opened
module Webhook_issues_pinned = Githubc2_components_webhook_issues_pinned
module Webhook_issues_reopened = Githubc2_components_webhook_issues_reopened
module Webhook_issues_transferred = Githubc2_components_webhook_issues_transferred
module Webhook_issues_typed = Githubc2_components_webhook_issues_typed
module Webhook_issues_unassigned = Githubc2_components_webhook_issues_unassigned
module Webhook_issues_unlabeled = Githubc2_components_webhook_issues_unlabeled
module Webhook_issues_unlocked = Githubc2_components_webhook_issues_unlocked
module Webhook_issues_unpinned = Githubc2_components_webhook_issues_unpinned
module Webhook_issues_untyped = Githubc2_components_webhook_issues_untyped
module Webhook_label_created = Githubc2_components_webhook_label_created
module Webhook_label_deleted = Githubc2_components_webhook_label_deleted
module Webhook_label_edited = Githubc2_components_webhook_label_edited

module Webhook_marketplace_purchase_cancelled =
  Githubc2_components_webhook_marketplace_purchase_cancelled

module Webhook_marketplace_purchase_changed =
  Githubc2_components_webhook_marketplace_purchase_changed

module Webhook_marketplace_purchase_pending_change =
  Githubc2_components_webhook_marketplace_purchase_pending_change

module Webhook_marketplace_purchase_pending_change_cancelled =
  Githubc2_components_webhook_marketplace_purchase_pending_change_cancelled

module Webhook_marketplace_purchase_purchased =
  Githubc2_components_webhook_marketplace_purchase_purchased

module Webhook_member_added = Githubc2_components_webhook_member_added
module Webhook_member_edited = Githubc2_components_webhook_member_edited
module Webhook_member_removed = Githubc2_components_webhook_member_removed
module Webhook_membership_added = Githubc2_components_webhook_membership_added
module Webhook_membership_removed = Githubc2_components_webhook_membership_removed

module Webhook_merge_group_checks_requested =
  Githubc2_components_webhook_merge_group_checks_requested

module Webhook_merge_group_destroyed = Githubc2_components_webhook_merge_group_destroyed
module Webhook_meta_deleted = Githubc2_components_webhook_meta_deleted
module Webhook_milestone_closed = Githubc2_components_webhook_milestone_closed
module Webhook_milestone_created = Githubc2_components_webhook_milestone_created
module Webhook_milestone_deleted = Githubc2_components_webhook_milestone_deleted
module Webhook_milestone_edited = Githubc2_components_webhook_milestone_edited
module Webhook_milestone_opened = Githubc2_components_webhook_milestone_opened
module Webhook_org_block_blocked = Githubc2_components_webhook_org_block_blocked
module Webhook_org_block_unblocked = Githubc2_components_webhook_org_block_unblocked
module Webhook_organization_deleted = Githubc2_components_webhook_organization_deleted
module Webhook_organization_member_added = Githubc2_components_webhook_organization_member_added
module Webhook_organization_member_invited = Githubc2_components_webhook_organization_member_invited
module Webhook_organization_member_removed = Githubc2_components_webhook_organization_member_removed
module Webhook_organization_renamed = Githubc2_components_webhook_organization_renamed
module Webhook_package_published = Githubc2_components_webhook_package_published
module Webhook_package_updated = Githubc2_components_webhook_package_updated
module Webhook_page_build = Githubc2_components_webhook_page_build

module Webhook_personal_access_token_request_approved =
  Githubc2_components_webhook_personal_access_token_request_approved

module Webhook_personal_access_token_request_cancelled =
  Githubc2_components_webhook_personal_access_token_request_cancelled

module Webhook_personal_access_token_request_created =
  Githubc2_components_webhook_personal_access_token_request_created

module Webhook_personal_access_token_request_denied =
  Githubc2_components_webhook_personal_access_token_request_denied

module Webhook_ping = Githubc2_components_webhook_ping
module Webhook_ping_form_encoded = Githubc2_components_webhook_ping_form_encoded
module Webhook_project_card_converted = Githubc2_components_webhook_project_card_converted
module Webhook_project_card_created = Githubc2_components_webhook_project_card_created
module Webhook_project_card_deleted = Githubc2_components_webhook_project_card_deleted
module Webhook_project_card_edited = Githubc2_components_webhook_project_card_edited
module Webhook_project_card_moved = Githubc2_components_webhook_project_card_moved
module Webhook_project_closed = Githubc2_components_webhook_project_closed
module Webhook_project_column_created = Githubc2_components_webhook_project_column_created
module Webhook_project_column_deleted = Githubc2_components_webhook_project_column_deleted
module Webhook_project_column_edited = Githubc2_components_webhook_project_column_edited
module Webhook_project_column_moved = Githubc2_components_webhook_project_column_moved
module Webhook_project_created = Githubc2_components_webhook_project_created
module Webhook_project_deleted = Githubc2_components_webhook_project_deleted
module Webhook_project_edited = Githubc2_components_webhook_project_edited
module Webhook_project_reopened = Githubc2_components_webhook_project_reopened
module Webhook_projects_v2_item_archived = Githubc2_components_webhook_projects_v2_item_archived
module Webhook_projects_v2_item_converted = Githubc2_components_webhook_projects_v2_item_converted
module Webhook_projects_v2_item_created = Githubc2_components_webhook_projects_v2_item_created
module Webhook_projects_v2_item_deleted = Githubc2_components_webhook_projects_v2_item_deleted
module Webhook_projects_v2_item_edited = Githubc2_components_webhook_projects_v2_item_edited
module Webhook_projects_v2_item_reordered = Githubc2_components_webhook_projects_v2_item_reordered
module Webhook_projects_v2_item_restored = Githubc2_components_webhook_projects_v2_item_restored
module Webhook_projects_v2_project_closed = Githubc2_components_webhook_projects_v2_project_closed
module Webhook_projects_v2_project_created = Githubc2_components_webhook_projects_v2_project_created
module Webhook_projects_v2_project_deleted = Githubc2_components_webhook_projects_v2_project_deleted
module Webhook_projects_v2_project_edited = Githubc2_components_webhook_projects_v2_project_edited

module Webhook_projects_v2_project_reopened =
  Githubc2_components_webhook_projects_v2_project_reopened

module Webhook_projects_v2_status_update_created =
  Githubc2_components_webhook_projects_v2_status_update_created

module Webhook_projects_v2_status_update_deleted =
  Githubc2_components_webhook_projects_v2_status_update_deleted

module Webhook_projects_v2_status_update_edited =
  Githubc2_components_webhook_projects_v2_status_update_edited

module Webhook_public = Githubc2_components_webhook_public
module Webhook_pull_request_assigned = Githubc2_components_webhook_pull_request_assigned

module Webhook_pull_request_auto_merge_disabled =
  Githubc2_components_webhook_pull_request_auto_merge_disabled

module Webhook_pull_request_auto_merge_enabled =
  Githubc2_components_webhook_pull_request_auto_merge_enabled

module Webhook_pull_request_closed = Githubc2_components_webhook_pull_request_closed

module Webhook_pull_request_converted_to_draft =
  Githubc2_components_webhook_pull_request_converted_to_draft

module Webhook_pull_request_demilestoned = Githubc2_components_webhook_pull_request_demilestoned
module Webhook_pull_request_dequeued = Githubc2_components_webhook_pull_request_dequeued
module Webhook_pull_request_edited = Githubc2_components_webhook_pull_request_edited
module Webhook_pull_request_enqueued = Githubc2_components_webhook_pull_request_enqueued
module Webhook_pull_request_labeled = Githubc2_components_webhook_pull_request_labeled
module Webhook_pull_request_locked = Githubc2_components_webhook_pull_request_locked
module Webhook_pull_request_milestoned = Githubc2_components_webhook_pull_request_milestoned
module Webhook_pull_request_opened = Githubc2_components_webhook_pull_request_opened

module Webhook_pull_request_ready_for_review =
  Githubc2_components_webhook_pull_request_ready_for_review

module Webhook_pull_request_reopened = Githubc2_components_webhook_pull_request_reopened

module Webhook_pull_request_review_comment_created =
  Githubc2_components_webhook_pull_request_review_comment_created

module Webhook_pull_request_review_comment_deleted =
  Githubc2_components_webhook_pull_request_review_comment_deleted

module Webhook_pull_request_review_comment_edited =
  Githubc2_components_webhook_pull_request_review_comment_edited

module Webhook_pull_request_review_dismissed =
  Githubc2_components_webhook_pull_request_review_dismissed

module Webhook_pull_request_review_edited = Githubc2_components_webhook_pull_request_review_edited

module Webhook_pull_request_review_request_removed =
  Githubc2_components_webhook_pull_request_review_request_removed

module Webhook_pull_request_review_requested =
  Githubc2_components_webhook_pull_request_review_requested

module Webhook_pull_request_review_submitted =
  Githubc2_components_webhook_pull_request_review_submitted

module Webhook_pull_request_review_thread_resolved =
  Githubc2_components_webhook_pull_request_review_thread_resolved

module Webhook_pull_request_review_thread_unresolved =
  Githubc2_components_webhook_pull_request_review_thread_unresolved

module Webhook_pull_request_synchronize = Githubc2_components_webhook_pull_request_synchronize
module Webhook_pull_request_unassigned = Githubc2_components_webhook_pull_request_unassigned
module Webhook_pull_request_unlabeled = Githubc2_components_webhook_pull_request_unlabeled
module Webhook_pull_request_unlocked = Githubc2_components_webhook_pull_request_unlocked
module Webhook_push = Githubc2_components_webhook_push
module Webhook_registry_package_published = Githubc2_components_webhook_registry_package_published
module Webhook_registry_package_updated = Githubc2_components_webhook_registry_package_updated
module Webhook_release_created = Githubc2_components_webhook_release_created
module Webhook_release_deleted = Githubc2_components_webhook_release_deleted
module Webhook_release_edited = Githubc2_components_webhook_release_edited
module Webhook_release_prereleased = Githubc2_components_webhook_release_prereleased
module Webhook_release_published = Githubc2_components_webhook_release_published
module Webhook_release_released = Githubc2_components_webhook_release_released
module Webhook_release_unpublished = Githubc2_components_webhook_release_unpublished

module Webhook_repository_advisory_published =
  Githubc2_components_webhook_repository_advisory_published

module Webhook_repository_advisory_reported =
  Githubc2_components_webhook_repository_advisory_reported

module Webhook_repository_archived = Githubc2_components_webhook_repository_archived
module Webhook_repository_created = Githubc2_components_webhook_repository_created
module Webhook_repository_deleted = Githubc2_components_webhook_repository_deleted
module Webhook_repository_dispatch_sample = Githubc2_components_webhook_repository_dispatch_sample
module Webhook_repository_edited = Githubc2_components_webhook_repository_edited
module Webhook_repository_import = Githubc2_components_webhook_repository_import
module Webhook_repository_privatized = Githubc2_components_webhook_repository_privatized
module Webhook_repository_publicized = Githubc2_components_webhook_repository_publicized
module Webhook_repository_renamed = Githubc2_components_webhook_repository_renamed
module Webhook_repository_ruleset_created = Githubc2_components_webhook_repository_ruleset_created
module Webhook_repository_ruleset_deleted = Githubc2_components_webhook_repository_ruleset_deleted
module Webhook_repository_ruleset_edited = Githubc2_components_webhook_repository_ruleset_edited
module Webhook_repository_transferred = Githubc2_components_webhook_repository_transferred
module Webhook_repository_unarchived = Githubc2_components_webhook_repository_unarchived

module Webhook_repository_vulnerability_alert_create =
  Githubc2_components_webhook_repository_vulnerability_alert_create

module Webhook_repository_vulnerability_alert_dismiss =
  Githubc2_components_webhook_repository_vulnerability_alert_dismiss

module Webhook_repository_vulnerability_alert_reopen =
  Githubc2_components_webhook_repository_vulnerability_alert_reopen

module Webhook_repository_vulnerability_alert_resolve =
  Githubc2_components_webhook_repository_vulnerability_alert_resolve

module Webhook_rubygems_metadata = Githubc2_components_webhook_rubygems_metadata

module Webhook_secret_scanning_alert_created =
  Githubc2_components_webhook_secret_scanning_alert_created

module Webhook_secret_scanning_alert_location_created =
  Githubc2_components_webhook_secret_scanning_alert_location_created

module Webhook_secret_scanning_alert_location_created_form_encoded =
  Githubc2_components_webhook_secret_scanning_alert_location_created_form_encoded

module Webhook_secret_scanning_alert_publicly_leaked =
  Githubc2_components_webhook_secret_scanning_alert_publicly_leaked

module Webhook_secret_scanning_alert_reopened =
  Githubc2_components_webhook_secret_scanning_alert_reopened

module Webhook_secret_scanning_alert_resolved =
  Githubc2_components_webhook_secret_scanning_alert_resolved

module Webhook_secret_scanning_alert_validated =
  Githubc2_components_webhook_secret_scanning_alert_validated

module Webhook_secret_scanning_scan_completed =
  Githubc2_components_webhook_secret_scanning_scan_completed

module Webhook_security_advisory_published = Githubc2_components_webhook_security_advisory_published
module Webhook_security_advisory_updated = Githubc2_components_webhook_security_advisory_updated
module Webhook_security_advisory_withdrawn = Githubc2_components_webhook_security_advisory_withdrawn
module Webhook_security_and_analysis = Githubc2_components_webhook_security_and_analysis
module Webhook_sponsorship_cancelled = Githubc2_components_webhook_sponsorship_cancelled
module Webhook_sponsorship_created = Githubc2_components_webhook_sponsorship_created
module Webhook_sponsorship_edited = Githubc2_components_webhook_sponsorship_edited

module Webhook_sponsorship_pending_cancellation =
  Githubc2_components_webhook_sponsorship_pending_cancellation

module Webhook_sponsorship_pending_tier_change =
  Githubc2_components_webhook_sponsorship_pending_tier_change

module Webhook_sponsorship_tier_changed = Githubc2_components_webhook_sponsorship_tier_changed
module Webhook_star_created = Githubc2_components_webhook_star_created
module Webhook_star_deleted = Githubc2_components_webhook_star_deleted
module Webhook_status = Githubc2_components_webhook_status

module Webhook_sub_issues_parent_issue_added =
  Githubc2_components_webhook_sub_issues_parent_issue_added

module Webhook_sub_issues_parent_issue_removed =
  Githubc2_components_webhook_sub_issues_parent_issue_removed

module Webhook_sub_issues_sub_issue_added = Githubc2_components_webhook_sub_issues_sub_issue_added

module Webhook_sub_issues_sub_issue_removed =
  Githubc2_components_webhook_sub_issues_sub_issue_removed

module Webhook_team_add = Githubc2_components_webhook_team_add
module Webhook_team_added_to_repository = Githubc2_components_webhook_team_added_to_repository
module Webhook_team_created = Githubc2_components_webhook_team_created
module Webhook_team_deleted = Githubc2_components_webhook_team_deleted
module Webhook_team_edited = Githubc2_components_webhook_team_edited

module Webhook_team_removed_from_repository =
  Githubc2_components_webhook_team_removed_from_repository

module Webhook_watch_started = Githubc2_components_webhook_watch_started
module Webhook_workflow_dispatch = Githubc2_components_webhook_workflow_dispatch
module Webhook_workflow_job_completed = Githubc2_components_webhook_workflow_job_completed
module Webhook_workflow_job_in_progress = Githubc2_components_webhook_workflow_job_in_progress
module Webhook_workflow_job_queued = Githubc2_components_webhook_workflow_job_queued
module Webhook_workflow_job_waiting = Githubc2_components_webhook_workflow_job_waiting
module Webhook_workflow_run_completed = Githubc2_components_webhook_workflow_run_completed
module Webhook_workflow_run_in_progress = Githubc2_components_webhook_workflow_run_in_progress
module Webhook_workflow_run_requested = Githubc2_components_webhook_workflow_run_requested
module Webhooks_alert = Githubc2_components_webhooks_alert
module Webhooks_answer = Githubc2_components_webhooks_answer
module Webhooks_approver = Githubc2_components_webhooks_approver
module Webhooks_changes = Githubc2_components_webhooks_changes
module Webhooks_changes_8 = Githubc2_components_webhooks_changes_8
module Webhooks_code_scanning_commit_oid = Githubc2_components_webhooks_code_scanning_commit_oid
module Webhooks_code_scanning_ref = Githubc2_components_webhooks_code_scanning_ref
module Webhooks_comment = Githubc2_components_webhooks_comment
module Webhooks_deploy_key = Githubc2_components_webhooks_deploy_key
module Webhooks_deploy_pusher_type = Githubc2_components_webhooks_deploy_pusher_type
module Webhooks_effective_date = Githubc2_components_webhooks_effective_date
module Webhooks_issue = Githubc2_components_webhooks_issue
module Webhooks_issue_2 = Githubc2_components_webhooks_issue_2
module Webhooks_issue_comment = Githubc2_components_webhooks_issue_comment
module Webhooks_label = Githubc2_components_webhooks_label
module Webhooks_marketplace_purchase = Githubc2_components_webhooks_marketplace_purchase
module Webhooks_membership = Githubc2_components_webhooks_membership
module Webhooks_milestone = Githubc2_components_webhooks_milestone
module Webhooks_milestone_3 = Githubc2_components_webhooks_milestone_3
module Webhooks_nullable_string = Githubc2_components_webhooks_nullable_string
module Webhooks_number = Githubc2_components_webhooks_number

module Webhooks_previous_marketplace_purchase =
  Githubc2_components_webhooks_previous_marketplace_purchase

module Webhooks_project = Githubc2_components_webhooks_project
module Webhooks_project_card = Githubc2_components_webhooks_project_card
module Webhooks_project_changes = Githubc2_components_webhooks_project_changes
module Webhooks_project_column = Githubc2_components_webhooks_project_column
module Webhooks_pull_request_5 = Githubc2_components_webhooks_pull_request_5
module Webhooks_ref_0 = Githubc2_components_webhooks_ref_0
module Webhooks_release = Githubc2_components_webhooks_release
module Webhooks_release_1 = Githubc2_components_webhooks_release_1
module Webhooks_repositories = Githubc2_components_webhooks_repositories
module Webhooks_repositories_added = Githubc2_components_webhooks_repositories_added
module Webhooks_repository_selection = Githubc2_components_webhooks_repository_selection
module Webhooks_review = Githubc2_components_webhooks_review
module Webhooks_review_comment = Githubc2_components_webhooks_review_comment
module Webhooks_reviewers = Githubc2_components_webhooks_reviewers
module Webhooks_rule = Githubc2_components_webhooks_rule
module Webhooks_security_advisory = Githubc2_components_webhooks_security_advisory
module Webhooks_sponsorship = Githubc2_components_webhooks_sponsorship
module Webhooks_team = Githubc2_components_webhooks_team
module Webhooks_team_1 = Githubc2_components_webhooks_team_1
module Webhooks_user = Githubc2_components_webhooks_user
module Webhooks_user_mannequin = Githubc2_components_webhooks_user_mannequin
module Webhooks_workflow = Githubc2_components_webhooks_workflow
module Webhooks_workflow_job_run = Githubc2_components_webhooks_workflow_job_run
module Workflow = Githubc2_components_workflow
module Workflow_run = Githubc2_components_workflow_run
module Workflow_run_usage = Githubc2_components_workflow_run_usage
module Workflow_usage = Githubc2_components_workflow_usage
