.PHONY: all release debug clean

all: release

release: install-tailwindcss

debug: install-tailwindcss

profile: install-tailwindcss

install-tailwindcss:
	mkdir -p node_modules
	npm install tailwindcss@1.4.6

clean:
