[package]
name = "json_of_yaml"
version = "0.1.0"
edition = "2021"

[lib]
name = "json_of_yaml"
crate-type = ["staticlib"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
serde_json = "1.0"
