= Writing a Request For Discussion
Malcolm Matalka <malcolm@terrateam.io>
2025-05-29
:source-highlighter: highlight.js
:toc:

== Status

In discussion

== Introduction

Communication is very important to Terrateam.  While many discussions are easy
to happen over a meeting or in chat, some discussions require so much context
and though to be effectively communicated that they require a long-form way to
communicating.  Terrateam has chosen an RFD as the form this should take.

RFDs are not unique to Terrateam.  The most prominent user of RFDs are Oxide.
However the basic structure has been taken from the RFC system that has existed
since the creation of the internet.

== Why RFDs?

We want to have RFDs for the following reasons:

. Historical record - For decisions that we make that are of substance, it is
useful to have a centralized store of them.  It also makes them searchable.
. Larger context - Some ideas require more context to entirely appreciate than
can be done in a meeting or in chat.  An RFD is the place where the author has
the reader's undivided attention and is able to give them all of the context
necessary to understand whatever is being discussed.


== When to write an RFD

There is no minimum requirement on when to write an RFD.  You should use your
discretion on when writing one would be valuable.

More importantly **do not** reject writing an RFD for any of these reasons:

. The idea is not fully formed.  That is OK.  An RFD is a valid place to explore
an idea and gather feedback.  The D stands for discussion.
. The idea is too small.  That is OK.  Even small ideas can be important.

In general, an RFD should almost definitely be written when:

. There is a change in architecture to the product.  Getting feedback from
multiple people improves the chances something will not be missed.
. There is a change that will impact many parts of the system.  Getting feedback
will help ensure that the change aligns with what other people are working on
and their view of the system.

== How to write an RFD

. Every RFD must be associated with a ticket in the
https://github.com/terrateamio/terrateam/issues[Terrateam] repository.
. Every commit for an RFD must have the ticket ID in the commit such that GitHub
can track it.
. An RFD is a subdirectory of the `rfds` directory.
. The directory must start with the ID of the ticket the RFD is being written
under.  It may contain a short description of it.
. The main file is called `index` and can be AsciiDoc, markdown, or a text file,
under the names `index.adoc`, `index.md`, and `index.txt` respectively.
. There are no requirements on sections, length, word usage, or formalism.  A
one sentence RFD is acceptable if that one sentence provides the sufficient
context to readers.
. The document must include a status in some form, describing the current state
of it.
. Other assets may be included in the directory in any way the author sees fit.
. A pull request is made with the RFD.
. Upon completion, the status is updated with if the RFD has been accepted or
rejected and it is merged.

NOTE: Rejected RFDs are STILL VALUABLE.  Ensure that they are merged as well so
that we can understand why a decision wasn't taken.

== How to read an RFD

. Try your best to read the RFD multiple times to ensure you understand it.
. Give constructive feedback.
