module Custom_attributes = struct
  type t = Gitlabc_components_api_entities_customattribute.t list
  [@@deriving yojson { strict = false; meta = true }, show, eq]
end

type t = {
  avatar_path : string option; [@default None]
  avatar_url : string option; [@default None]
  bio : string option; [@default None]
  bot : string option; [@default None]
  created_at : string option; [@default None]
  custom_attributes : Custom_attributes.t option; [@default None]
  discord : string option; [@default None]
  followers : string option; [@default None]
  following : string option; [@default None]
  id : int option; [@default None]
  is_followed : string option; [@default None]
  job_title : string option; [@default None]
  linkedin : string option; [@default None]
  local_time : string option; [@default None]
  location : string option; [@default None]
  locked : bool option; [@default None]
  name : string option; [@default None]
  organization : string option; [@default None]
  pronouns : string option; [@default None]
  public_email : string option; [@default None]
  skype : string option; [@default None]
  state : string option; [@default None]
  twitter : string option; [@default None]
  username : string option; [@default None]
  web_url : string option; [@default None]
  website_url : string option; [@default None]
  work_information : string option; [@default None]
}
[@@deriving yojson { strict = false; meta = true }, show, eq]
