type t = {
  before_sha : string option; [@default None]
  committed_at : string option; [@default None]
  coverage : float option; [@default None]
  created_at : string option; [@default None]
  detailed_status : Gitlabc_components_detailedstatusentity.t option; [@default None]
  duration : int option; [@default None]
  finished_at : string option; [@default None]
  id : int option; [@default None]
  iid : int option; [@default None]
  project_id : int option; [@default None]
  queued_duration : int option; [@default None]
  ref_ : string option; [@default None] [@key "ref"]
  sha : string option; [@default None]
  source : string option; [@default None]
  started_at : string option; [@default None]
  status : string option; [@default None]
  tag : bool option; [@default None]
  updated_at : string option; [@default None]
  user : Gitlabc_components_api_entities_userbasic.t option; [@default None]
  web_url : string option; [@default None]
  yaml_errors : string option; [@default None]
}
[@@deriving yojson { strict = false; meta = true }, show, eq]
