type t = {
  admin : bool option; [@default None]
  auditor : bool option; [@default None]
  avatar : string option; [@default None]
  bio : string option; [@default None]
  can_create_group : bool option; [@default None]
  color_scheme_id : int option; [@default None]
  commit_email : string option; [@default None]
  discord : string option; [@default None]
  email : string;
  extern_uid : string option; [@default None]
  external_ : bool option; [@default None] [@key "external"]
  extra_shared_runners_minutes_limit : int option; [@default None]
  force_random_password : bool option; [@default None]
  group_id_for_saml : int option; [@default None]
  linkedin : string option; [@default None]
  location : string option; [@default None]
  name : string;
  note : string option; [@default None]
  organization : string option; [@default None]
  password : string option; [@default None]
  private_profile : bool option; [@default None]
  projects_limit : int option; [@default None]
  pronouns : string option; [@default None]
  provider : string option; [@default None]
  public_email : string option; [@default None]
  reset_password : bool option; [@default None]
  shared_runners_minutes_limit : int option; [@default None]
  skip_confirmation : bool option; [@default None]
  skype : string option; [@default None]
  theme_id : int option; [@default None]
  twitter : string option; [@default None]
  username : string;
  view_diffs_file_by_file : bool option; [@default None]
  website_url : string option; [@default None]
}
[@@deriving yojson { strict = false; meta = true }, show, eq]
