type t = {
  alert_channel : string option; [@default None]
  branches_to_be_notified : string option; [@default None]
  channel : string option; [@default None]
  confidential_issue_channel : string option; [@default None]
  confidential_issues_events : bool option; [@default None]
  confidential_note_channel : string option; [@default None]
  confidential_note_events : bool option; [@default None]
  deployment_channel : string option; [@default None]
  deployment_events : bool option; [@default None]
  incident_channel : string option; [@default None]
  incident_events : bool option; [@default None]
  issue_channel : string option; [@default None]
  issues_events : bool option; [@default None]
  labels_to_be_notified : string option; [@default None]
  labels_to_be_notified_behavior : string option; [@default None]
  merge_request_channel : string option; [@default None]
  merge_requests_events : bool option; [@default None]
  note_channel : string option; [@default None]
  note_events : bool option; [@default None]
  notify_only_broken_pipelines : bool option; [@default None]
  pipeline_channel : string option; [@default None]
  pipeline_events : bool option; [@default None]
  push_channel : string option; [@default None]
  push_events : bool option; [@default None]
  tag_push_channel : string option; [@default None]
  tag_push_events : bool option; [@default None]
  use_inherited_settings : bool option; [@default None]
  username : string option; [@default None]
  vulnerability_channel : string option; [@default None]
  vulnerability_events : bool option; [@default None]
  webhook : string;
  wiki_page_channel : string option; [@default None]
  wiki_page_events : bool option; [@default None]
}
[@@deriving yojson { strict = false; meta = true }, show, eq]
