module API_Entities_AccessRequester = Gitlabc_components_api_entities_accessrequester
module API_Entities_Application = Gitlabc_components_api_entities_application
module API_Entities_ApplicationWithSecret = Gitlabc_components_api_entities_applicationwithsecret
module API_Entities_Approvals = Gitlabc_components_api_entities_approvals
module API_Entities_Avatar = Gitlabc_components_api_entities_avatar
module API_Entities_AwardEmoji = Gitlabc_components_api_entities_awardemoji
module API_Entities_Badge = Gitlabc_components_api_entities_badge
module API_Entities_BasicBadgeDetails = Gitlabc_components_api_entities_basicbadgedetails
module API_Entities_BasicGroupDetails = Gitlabc_components_api_entities_basicgroupdetails
module API_Entities_BasicProjectDetails = Gitlabc_components_api_entities_basicprojectdetails
module API_Entities_BasicRef = Gitlabc_components_api_entities_basicref

module API_Entities_BatchedBackgroundMigration =
  Gitlabc_components_api_entities_batchedbackgroundmigration

module API_Entities_Branch = Gitlabc_components_api_entities_branch

module API_Entities_BulkImports_ExportBatchStatus =
  Gitlabc_components_api_entities_bulkimports_exportbatchstatus

module API_Entities_BulkImports_ExportStatus =
  Gitlabc_components_api_entities_bulkimports_exportstatus

module API_Entities_Changelog = Gitlabc_components_api_entities_changelog
module API_Entities_Ci_Bridge = Gitlabc_components_api_entities_ci_bridge

module API_Entities_Ci_Catalog_Resources_Version =
  Gitlabc_components_api_entities_ci_catalog_resources_version

module API_Entities_Ci_Job = Gitlabc_components_api_entities_ci_job
module API_Entities_Ci_JobArtifact = Gitlabc_components_api_entities_ci_jobartifact
module API_Entities_Ci_JobArtifactFile = Gitlabc_components_api_entities_ci_jobartifactfile
module API_Entities_Ci_JobBasic = Gitlabc_components_api_entities_ci_jobbasic
module API_Entities_Ci_JobBasicWithProject = Gitlabc_components_api_entities_ci_jobbasicwithproject
module API_Entities_Ci_Lint_Result = Gitlabc_components_api_entities_ci_lint_result
module API_Entities_Ci_Lint_Result_Include = Gitlabc_components_api_entities_ci_lint_result_include
module API_Entities_Ci_Pipeline = Gitlabc_components_api_entities_ci_pipeline
module API_Entities_Ci_PipelineBasic = Gitlabc_components_api_entities_ci_pipelinebasic
module API_Entities_Ci_PipelineSchedule = Gitlabc_components_api_entities_ci_pipelineschedule

module API_Entities_Ci_PipelineScheduleDetails =
  Gitlabc_components_api_entities_ci_pipelinescheduledetails

module API_Entities_Ci_PipelineWithMetadata =
  Gitlabc_components_api_entities_ci_pipelinewithmetadata

module API_Entities_Ci_ResetTokenResult = Gitlabc_components_api_entities_ci_resettokenresult
module API_Entities_Ci_ResourceGroup = Gitlabc_components_api_entities_ci_resourcegroup
module API_Entities_Ci_Runner = Gitlabc_components_api_entities_ci_runner
module API_Entities_Ci_RunnerDetails = Gitlabc_components_api_entities_ci_runnerdetails
module API_Entities_Ci_RunnerManager = Gitlabc_components_api_entities_ci_runnermanager

module API_Entities_Ci_RunnerRegistrationDetails =
  Gitlabc_components_api_entities_ci_runnerregistrationdetails

module API_Entities_Ci_SecureFile = Gitlabc_components_api_entities_ci_securefile
module API_Entities_Ci_Variable = Gitlabc_components_api_entities_ci_variable
module API_Entities_Cluster = Gitlabc_components_api_entities_cluster
module API_Entities_ClusterGroup = Gitlabc_components_api_entities_clustergroup
module API_Entities_ClusterProject = Gitlabc_components_api_entities_clusterproject
module API_Entities_Clusters_Agent = Gitlabc_components_api_entities_clusters_agent
module API_Entities_Clusters_AgentToken = Gitlabc_components_api_entities_clusters_agenttoken

module API_Entities_Clusters_AgentTokenBasic =
  Gitlabc_components_api_entities_clusters_agenttokenbasic

module API_Entities_Clusters_AgentTokenWithToken =
  Gitlabc_components_api_entities_clusters_agenttokenwithtoken

module API_Entities_Commit = Gitlabc_components_api_entities_commit
module API_Entities_CommitDetail = Gitlabc_components_api_entities_commitdetail
module API_Entities_CommitNote = Gitlabc_components_api_entities_commitnote
module API_Entities_CommitSequence = Gitlabc_components_api_entities_commitsequence
module API_Entities_CommitSignature = Gitlabc_components_api_entities_commitsignature
module API_Entities_CommitStats = Gitlabc_components_api_entities_commitstats
module API_Entities_CommitStatus = Gitlabc_components_api_entities_commitstatus
module API_Entities_Compare = Gitlabc_components_api_entities_compare

module API_Entities_ConanPackage_ConanPackageManifest =
  Gitlabc_components_api_entities_conanpackage_conanpackagemanifest

module API_Entities_ConanPackage_ConanPackageSnapshot =
  Gitlabc_components_api_entities_conanpackage_conanpackagesnapshot

module API_Entities_ConanPackage_ConanRecipeManifest =
  Gitlabc_components_api_entities_conanpackage_conanrecipemanifest

module API_Entities_ConanPackage_ConanRecipeSnapshot =
  Gitlabc_components_api_entities_conanpackage_conanrecipesnapshot

module API_Entities_ConanPackage_ConanUploadUrls =
  Gitlabc_components_api_entities_conanpackage_conanuploadurls

module API_Entities_ContainerExpirationPolicy =
  Gitlabc_components_api_entities_containerexpirationpolicy

module API_Entities_ContainerRegistry_Repository =
  Gitlabc_components_api_entities_containerregistry_repository

module API_Entities_ContainerRegistry_Tag = Gitlabc_components_api_entities_containerregistry_tag

module API_Entities_ContainerRegistry_TagDetails =
  Gitlabc_components_api_entities_containerregistry_tagdetails

module API_Entities_Contributor = Gitlabc_components_api_entities_contributor
module API_Entities_CustomAttribute = Gitlabc_components_api_entities_customattribute
module API_Entities_DeployKey = Gitlabc_components_api_entities_deploykey
module API_Entities_DeployKeysProject = Gitlabc_components_api_entities_deploykeysproject
module API_Entities_DeployToken = Gitlabc_components_api_entities_deploytoken
module API_Entities_DeployTokenWithToken = Gitlabc_components_api_entities_deploytokenwithtoken
module API_Entities_Deployment = Gitlabc_components_api_entities_deployment
module API_Entities_DeploymentExtended = Gitlabc_components_api_entities_deploymentextended
module API_Entities_Deployments_Approval = Gitlabc_components_api_entities_deployments_approval

module API_Entities_Deployments_ApprovalSummary =
  Gitlabc_components_api_entities_deployments_approvalsummary

module API_Entities_Dictionary_Table = Gitlabc_components_api_entities_dictionary_table
module API_Entities_Diff = Gitlabc_components_api_entities_diff
module API_Entities_DiffRefs = Gitlabc_components_api_entities_diffrefs
module API_Entities_DraftNote = Gitlabc_components_api_entities_draftnote
module API_Entities_Email = Gitlabc_components_api_entities_email
module API_Entities_Environment = Gitlabc_components_api_entities_environment
module API_Entities_EnvironmentBasic = Gitlabc_components_api_entities_environmentbasic

module API_Entities_ErrorTracking_ClientKey =
  Gitlabc_components_api_entities_errortracking_clientkey

module API_Entities_ErrorTracking_ProjectSetting =
  Gitlabc_components_api_entities_errortracking_projectsetting

module API_Entities_Event = Gitlabc_components_api_entities_event
module API_Entities_FeatureFlag = Gitlabc_components_api_entities_featureflag

module API_Entities_FeatureFlag_BasicUserList =
  Gitlabc_components_api_entities_featureflag_basicuserlist

module API_Entities_FeatureFlag_Scope = Gitlabc_components_api_entities_featureflag_scope
module API_Entities_FeatureFlag_Strategy = Gitlabc_components_api_entities_featureflag_strategy
module API_Entities_FeatureFlag_UserList = Gitlabc_components_api_entities_featureflag_userlist
module API_Entities_FreezePeriod = Gitlabc_components_api_entities_freezeperiod
module API_Entities_GoModuleVersion = Gitlabc_components_api_entities_gomoduleversion
module API_Entities_GpgKey = Gitlabc_components_api_entities_gpgkey
module API_Entities_Group = Gitlabc_components_api_entities_group
module API_Entities_GroupAccess = Gitlabc_components_api_entities_groupaccess
module API_Entities_GroupDetail = Gitlabc_components_api_entities_groupdetail
module API_Entities_Identity = Gitlabc_components_api_entities_identity
module API_Entities_ImpersonationToken = Gitlabc_components_api_entities_impersonationtoken

module API_Entities_ImpersonationTokenWithToken =
  Gitlabc_components_api_entities_impersonationtokenwithtoken

module API_Entities_Integration = Gitlabc_components_api_entities_integration
module API_Entities_IntegrationBasic = Gitlabc_components_api_entities_integrationbasic
module API_Entities_Invitation = Gitlabc_components_api_entities_invitation
module API_Entities_IssuableReferences = Gitlabc_components_api_entities_issuablereferences
module API_Entities_IssuableTimeStats = Gitlabc_components_api_entities_issuabletimestats
module API_Entities_IssueBasic = Gitlabc_components_api_entities_issuebasic
module API_Entities_IssueLink = Gitlabc_components_api_entities_issuelink
module API_Entities_Iteration = Gitlabc_components_api_entities_iteration
module API_Entities_License = Gitlabc_components_api_entities_license
module API_Entities_LicenseBasic = Gitlabc_components_api_entities_licensebasic
module API_Entities_MRNote = Gitlabc_components_api_entities_mrnote
module API_Entities_MarkdownUploadAdmin = Gitlabc_components_api_entities_markdownuploadadmin
module API_Entities_Member = Gitlabc_components_api_entities_member
module API_Entities_Membership = Gitlabc_components_api_entities_membership
module API_Entities_MergeRequest = Gitlabc_components_api_entities_mergerequest
module API_Entities_MergeRequestApprovals = Gitlabc_components_api_entities_mergerequestapprovals
module API_Entities_MergeRequestBasic = Gitlabc_components_api_entities_mergerequestbasic
module API_Entities_MergeRequestChanges = Gitlabc_components_api_entities_mergerequestchanges
module API_Entities_MergeRequestDiff = Gitlabc_components_api_entities_mergerequestdiff
module API_Entities_MergeRequestDiffFull = Gitlabc_components_api_entities_mergerequestdifffull
module API_Entities_MergeRequestReviewer = Gitlabc_components_api_entities_mergerequestreviewer
module API_Entities_Metadata = Gitlabc_components_api_entities_metadata
module API_Entities_MetricImage = Gitlabc_components_api_entities_metricimage
module API_Entities_Milestone = Gitlabc_components_api_entities_milestone
module API_Entities_MilestoneWithStats = Gitlabc_components_api_entities_milestonewithstats
module API_Entities_NamespaceBasic = Gitlabc_components_api_entities_namespacebasic

module API_Entities_Namespace_RootStorageStatistics =
  Gitlabc_components_api_entities_namespace_rootstoragestatistics

module API_Entities_Note = Gitlabc_components_api_entities_note
module API_Entities_NpmPackage = Gitlabc_components_api_entities_npmpackage
module API_Entities_NpmPackageTag = Gitlabc_components_api_entities_npmpackagetag
module API_Entities_Nuget_Dependency = Gitlabc_components_api_entities_nuget_dependency
module API_Entities_Nuget_DependencyGroup = Gitlabc_components_api_entities_nuget_dependencygroup
module API_Entities_Nuget_PackageMetadata = Gitlabc_components_api_entities_nuget_packagemetadata

module API_Entities_Nuget_PackageMetadataCatalogEntry =
  Gitlabc_components_api_entities_nuget_packagemetadatacatalogentry

module API_Entities_Nuget_PackagesMetadata = Gitlabc_components_api_entities_nuget_packagesmetadata

module API_Entities_Nuget_PackagesMetadataItem =
  Gitlabc_components_api_entities_nuget_packagesmetadataitem

module API_Entities_Nuget_PackagesVersions = Gitlabc_components_api_entities_nuget_packagesversions
module API_Entities_Nuget_SearchResult = Gitlabc_components_api_entities_nuget_searchresult

module API_Entities_Nuget_SearchResultVersion =
  Gitlabc_components_api_entities_nuget_searchresultversion

module API_Entities_Nuget_SearchResults = Gitlabc_components_api_entities_nuget_searchresults
module API_Entities_Nuget_ServiceIndex = Gitlabc_components_api_entities_nuget_serviceindex
module API_Entities_Package = Gitlabc_components_api_entities_package
module API_Entities_PackageFile = Gitlabc_components_api_entities_packagefile
module API_Entities_PackageVersion = Gitlabc_components_api_entities_packageversion
module API_Entities_Package_Pipeline = Gitlabc_components_api_entities_package_pipeline

module API_Entities_Packages_Debian_Distribution =
  Gitlabc_components_api_entities_packages_debian_distribution

module API_Entities_PagesDomain = Gitlabc_components_api_entities_pagesdomain
module API_Entities_PagesDomainCertificate = Gitlabc_components_api_entities_pagesdomaincertificate

module API_Entities_PersonalAccessTokenWithToken =
  Gitlabc_components_api_entities_personalaccesstokenwithtoken

module API_Entities_Platform_Kubernetes = Gitlabc_components_api_entities_platform_kubernetes
module API_Entities_Project = Gitlabc_components_api_entities_project
module API_Entities_ProjectAccess = Gitlabc_components_api_entities_projectaccess
module API_Entities_ProjectDailyFetches = Gitlabc_components_api_entities_projectdailyfetches
module API_Entities_ProjectDailyStatistics = Gitlabc_components_api_entities_projectdailystatistics
module API_Entities_ProjectExportStatus = Gitlabc_components_api_entities_projectexportstatus
module API_Entities_ProjectGroupLink = Gitlabc_components_api_entities_projectgrouplink
module API_Entities_ProjectHook = Gitlabc_components_api_entities_projecthook
module API_Entities_ProjectIdentity = Gitlabc_components_api_entities_projectidentity

module API_Entities_ProjectImportFailedRelation =
  Gitlabc_components_api_entities_projectimportfailedrelation

module API_Entities_ProjectImportStatus = Gitlabc_components_api_entities_projectimportstatus
module API_Entities_ProjectJobTokenScope = Gitlabc_components_api_entities_projectjobtokenscope

module API_Entities_ProjectRepositoryStorage =
  Gitlabc_components_api_entities_projectrepositorystorage

module API_Entities_ProjectSnippet = Gitlabc_components_api_entities_projectsnippet
module API_Entities_ProjectStatistics = Gitlabc_components_api_entities_projectstatistics
module API_Entities_ProjectUpload = Gitlabc_components_api_entities_projectupload
module API_Entities_ProjectWithAccess = Gitlabc_components_api_entities_projectwithaccess

module API_Entities_Projects_ContainerRegistry_Protection_Rule =
  Gitlabc_components_api_entities_projects_containerregistry_protection_rule

module API_Entities_Projects_Packages_Protection_Rule =
  Gitlabc_components_api_entities_projects_packages_protection_rule

module API_Entities_Projects_RepositoryStorageMove =
  Gitlabc_components_api_entities_projects_repositorystoragemove

module API_Entities_ProtectedBranch = Gitlabc_components_api_entities_protectedbranch

module API_Entities_ProtectedEnvironments_ApprovalRuleForSummary =
  Gitlabc_components_api_entities_protectedenvironments_approvalruleforsummary

module API_Entities_ProtectedRefAccess = Gitlabc_components_api_entities_protectedrefaccess
module API_Entities_ProtectedTag = Gitlabc_components_api_entities_protectedtag
module API_Entities_Provider_Gcp = Gitlabc_components_api_entities_provider_gcp
module API_Entities_PublicGroupDetails = Gitlabc_components_api_entities_publicgroupdetails
module API_Entities_PushEventPayload = Gitlabc_components_api_entities_pusheventpayload
module API_Entities_RelatedIssue = Gitlabc_components_api_entities_relatedissue
module API_Entities_RelationImportTracker = Gitlabc_components_api_entities_relationimporttracker
module API_Entities_Release = Gitlabc_components_api_entities_release
module API_Entities_Releases_Evidence = Gitlabc_components_api_entities_releases_evidence
module API_Entities_Releases_Link = Gitlabc_components_api_entities_releases_link
module API_Entities_Releases_Source = Gitlabc_components_api_entities_releases_source
module API_Entities_RemoteMirror = Gitlabc_components_api_entities_remotemirror
module API_Entities_ResourceAccessToken = Gitlabc_components_api_entities_resourceaccesstoken

module API_Entities_ResourceAccessTokenWithToken =
  Gitlabc_components_api_entities_resourceaccesstokenwithtoken

module API_Entities_ResourceMilestoneEvent = Gitlabc_components_api_entities_resourcemilestoneevent
module API_Entities_SSHKey = Gitlabc_components_api_entities_sshkey
module API_Entities_ScimIdentity = Gitlabc_components_api_entities_scimidentity
module API_Entities_Tag = Gitlabc_components_api_entities_tag
module API_Entities_TagRelease = Gitlabc_components_api_entities_tagrelease
module API_Entities_TagSignature = Gitlabc_components_api_entities_tagsignature
module API_Entities_TemplatesList = Gitlabc_components_api_entities_templateslist
module API_Entities_TreeObject = Gitlabc_components_api_entities_treeobject
module API_Entities_Trigger = Gitlabc_components_api_entities_trigger
module API_Entities_User = Gitlabc_components_api_entities_user
module API_Entities_UserAgentDetail = Gitlabc_components_api_entities_useragentdetail
module API_Entities_UserBasic = Gitlabc_components_api_entities_userbasic
module API_Entities_UserCounts = Gitlabc_components_api_entities_usercounts

module API_Entities_UserCreditCardValidations =
  Gitlabc_components_api_entities_usercreditcardvalidations

module API_Entities_UserPreferences = Gitlabc_components_api_entities_userpreferences
module API_Entities_UserPublic = Gitlabc_components_api_entities_userpublic
module API_Entities_UserSafe = Gitlabc_components_api_entities_usersafe
module API_Entities_UserStatus = Gitlabc_components_api_entities_userstatus
module API_Entities_UserSupportPin = Gitlabc_components_api_entities_usersupportpin
module API_Entities_UserWithAdmin = Gitlabc_components_api_entities_userwithadmin
module API_Entities_WikiAttachment = Gitlabc_components_api_entities_wikiattachment
module API_Entities_WikiPage = Gitlabc_components_api_entities_wikipage
module API_Entities_WikiPageBasic = Gitlabc_components_api_entities_wikipagebasic
module DetailedStatusEntity = Gitlabc_components_detailedstatusentity
module EE_API_Entities_ApprovalRuleShort = Gitlabc_components_ee_api_entities_approvalruleshort
module EE_API_Entities_ApprovalState = Gitlabc_components_ee_api_entities_approvalstate
module EE_API_Entities_AuditEvent = Gitlabc_components_ee_api_entities_auditevent
module EE_API_Entities_BillableMembership = Gitlabc_components_ee_api_entities_billablemembership
module EE_API_Entities_LdapGroupLink = Gitlabc_components_ee_api_entities_ldapgrouplink
module EE_API_Entities_MemberRole = Gitlabc_components_ee_api_entities_memberrole

module EE_API_Entities_MergeRequestApprovalRule_SourceRule =
  Gitlabc_components_ee_api_entities_mergerequestapprovalrule_sourcerule

module EE_API_Entities_MergeRequestApprovalState =
  Gitlabc_components_ee_api_entities_mergerequestapprovalstate

module EE_API_Entities_MergeRequestApprovalStateRule =
  Gitlabc_components_ee_api_entities_mergerequestapprovalstaterule

module EE_API_Entities_SamlGroupLink = Gitlabc_components_ee_api_entities_samlgrouplink
module EE_API_Entities_SshCertificate = Gitlabc_components_ee_api_entities_sshcertificate
module EpicBaseEntity = Gitlabc_components_epicbaseentity
module TestCaseEntity = Gitlabc_components_testcaseentity
module TestReportEntity = Gitlabc_components_testreportentity
module TestReportSummaryEntity = Gitlabc_components_testreportsummaryentity
module TestSuiteEntity = Gitlabc_components_testsuiteentity
module TestSuiteSummaryEntity = Gitlabc_components_testsuitesummaryentity

module PatchApiV4ProjectsIdErrorTrackingSettings =
  Gitlabc_components_patchapiv4projectsiderrortrackingsettings

module PatchApiV4ProjectsIdJobTokenScope = Gitlabc_components_patchapiv4projectsidjobtokenscope

module PatchApiV4ProjectsIdPackagesProtectionRulesPackageProtectionRuleId =
  Gitlabc_components_patchapiv4projectsidpackagesprotectionrulespackageprotectionruleid

module PatchApiV4ProjectsIdPages = Gitlabc_components_patchapiv4projectsidpages

module PatchApiV4ProjectsIdProtectedBranchesName =
  Gitlabc_components_patchapiv4projectsidprotectedbranchesname

module PatchApiV4ProjectsIdRegistryProtectionRepositoryRulesProtectionRuleId =
  Gitlabc_components_patchapiv4projectsidregistryprotectionrepositoryrulesprotectionruleid

module PatchApiV4UserStatus = Gitlabc_components_patchapiv4userstatus
module PostApiV4AdminCiVariables = Gitlabc_components_postapiv4admincivariables
module PostApiV4AdminClustersAdd = Gitlabc_components_postapiv4adminclustersadd

module PostApiV4AdminMigrationsTimestampMark =
  Gitlabc_components_postapiv4adminmigrationstimestampmark

module PostApiV4Applications = Gitlabc_components_postapiv4applications
module PostApiV4Groups = Gitlabc_components_postapiv4groups
module PostApiV4GroupsIdAccessTokens = Gitlabc_components_postapiv4groupsidaccesstokens

module PostApiV4GroupsIdAccessTokensSelfRotate =
  Gitlabc_components_postapiv4groupsidaccesstokensselfrotate

module PostApiV4GroupsIdAccessTokensTokenIdRotate =
  Gitlabc_components_postapiv4groupsidaccesstokenstokenidrotate

module PostApiV4GroupsIdBadges = Gitlabc_components_postapiv4groupsidbadges
module PostApiV4GroupsIdClustersUser = Gitlabc_components_postapiv4groupsidclustersuser

module PostApiV4GroupsIdDebianDistributions =
  Gitlabc_components_postapiv4groupsiddebiandistributions

module PostApiV4GroupsIdDeployTokens = Gitlabc_components_postapiv4groupsiddeploytokens

module PostApiV4GroupsIdEpicsEpicIidAwardEmoji =
  Gitlabc_components_postapiv4groupsidepicsepiciidawardemoji

module PostApiV4GroupsIdEpicsEpicIidNotesNoteIdAwardEmoji =
  Gitlabc_components_postapiv4groupsidepicsepiciidnotesnoteidawardemoji

module PostApiV4GroupsIdExportRelations = Gitlabc_components_postapiv4groupsidexportrelations
module PostApiV4GroupsIdInvitations = Gitlabc_components_postapiv4groupsidinvitations
module PostApiV4GroupsIdMembers = Gitlabc_components_postapiv4groupsidmembers
module PostApiV4GroupsIdShare = Gitlabc_components_postapiv4groupsidshare
module PostApiV4GroupsIdSshCertificates = Gitlabc_components_postapiv4groupsidsshcertificates
module PostApiV4GroupsIdTokensRevoke = Gitlabc_components_postapiv4groupsidtokensrevoke
module PostApiV4GroupsIdTransfer = Gitlabc_components_postapiv4groupsidtransfer
module PostApiV4GroupsIdVariables = Gitlabc_components_postapiv4groupsidvariables
module PostApiV4GroupsIdWikis = Gitlabc_components_postapiv4groupsidwikis
module PostApiV4GroupsIdWikisAttachments = Gitlabc_components_postapiv4groupsidwikisattachments

module PostApiV4ProjectsId_refRef_triggerPipeline =
  Gitlabc_components_postapiv4projectsid_refref_triggerpipeline

module PostApiV4ProjectsIdAccessTokens = Gitlabc_components_postapiv4projectsidaccesstokens

module PostApiV4ProjectsIdAccessTokensSelfRotate =
  Gitlabc_components_postapiv4projectsidaccesstokensselfrotate

module PostApiV4ProjectsIdAccessTokensTokenIdRotate =
  Gitlabc_components_postapiv4projectsidaccesstokenstokenidrotate

module PostApiV4ProjectsIdBadges = Gitlabc_components_postapiv4projectsidbadges
module PostApiV4ProjectsIdCatalogPublish = Gitlabc_components_postapiv4projectsidcatalogpublish
module PostApiV4ProjectsIdCiLint = Gitlabc_components_postapiv4projectsidcilint
module PostApiV4ProjectsIdClusterAgents = Gitlabc_components_postapiv4projectsidclusteragents

module PostApiV4ProjectsIdClusterAgentsAgentIdTokens =
  Gitlabc_components_postapiv4projectsidclusteragentsagentidtokens

module PostApiV4ProjectsIdClustersUser = Gitlabc_components_postapiv4projectsidclustersuser

module PostApiV4ProjectsIdDebianDistributions =
  Gitlabc_components_postapiv4projectsiddebiandistributions

module PostApiV4ProjectsIdDeployKeys = Gitlabc_components_postapiv4projectsiddeploykeys
module PostApiV4ProjectsIdDeployTokens = Gitlabc_components_postapiv4projectsiddeploytokens
module PostApiV4ProjectsIdDeployments = Gitlabc_components_postapiv4projectsiddeployments

module PostApiV4ProjectsIdDeploymentsDeploymentIdApproval =
  Gitlabc_components_postapiv4projectsiddeploymentsdeploymentidapproval

module PostApiV4ProjectsIdEnvironments = Gitlabc_components_postapiv4projectsidenvironments

module PostApiV4ProjectsIdEnvironmentsEnvironmentIdStop =
  Gitlabc_components_postapiv4projectsidenvironmentsenvironmentidstop

module PostApiV4ProjectsIdEnvironmentsStopStale =
  Gitlabc_components_postapiv4projectsidenvironmentsstopstale

module PostApiV4ProjectsIdExport = Gitlabc_components_postapiv4projectsidexport
module PostApiV4ProjectsIdExportRelations = Gitlabc_components_postapiv4projectsidexportrelations
module PostApiV4ProjectsIdFeatureFlags = Gitlabc_components_postapiv4projectsidfeatureflags

module PostApiV4ProjectsIdFeatureFlagsUserLists =
  Gitlabc_components_postapiv4projectsidfeatureflagsuserlists

module PostApiV4ProjectsIdFork = Gitlabc_components_postapiv4projectsidfork
module PostApiV4ProjectsIdFreezePeriods = Gitlabc_components_postapiv4projectsidfreezeperiods
module PostApiV4ProjectsIdHooks = Gitlabc_components_postapiv4projectsidhooks
module PostApiV4ProjectsIdHousekeeping = Gitlabc_components_postapiv4projectsidhousekeeping

module PostApiV4ProjectsIdIntegrationsMattermostSlashCommandsTrigger =
  Gitlabc_components_postapiv4projectsidintegrationsmattermostslashcommandstrigger

module PostApiV4ProjectsIdIntegrationsSlackSlashCommandsTrigger =
  Gitlabc_components_postapiv4projectsidintegrationsslackslashcommandstrigger

module PostApiV4ProjectsIdInvitations = Gitlabc_components_postapiv4projectsidinvitations

module PostApiV4ProjectsIdIssuesIssueIidAwardEmoji =
  Gitlabc_components_postapiv4projectsidissuesissueiidawardemoji

module PostApiV4ProjectsIdIssuesIssueIidLinks =
  Gitlabc_components_postapiv4projectsidissuesissueiidlinks

module PostApiV4ProjectsIdIssuesIssueIidNotesNoteIdAwardEmoji =
  Gitlabc_components_postapiv4projectsidissuesissueiidnotesnoteidawardemoji

module PostApiV4ProjectsIdJobTokenScopeAllowlist =
  Gitlabc_components_postapiv4projectsidjobtokenscopeallowlist

module PostApiV4ProjectsIdJobTokenScopeGroupsAllowlist =
  Gitlabc_components_postapiv4projectsidjobtokenscopegroupsallowlist

module PostApiV4ProjectsIdJobsJobIdPlay = Gitlabc_components_postapiv4projectsidjobsjobidplay
module PostApiV4ProjectsIdMembers = Gitlabc_components_postapiv4projectsidmembers
module PostApiV4ProjectsIdMergeRequests = Gitlabc_components_postapiv4projectsidmergerequests

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidAddSpentTime =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidaddspenttime

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidApprovals =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidapprovals

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidApprove =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidapprove

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidAwardEmoji =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidawardemoji

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidContextCommits =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidcontextcommits

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotes =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiiddraftnotes

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidNotesNoteIdAwardEmoji =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidnotesnoteidawardemoji

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidPipelines =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidpipelines

module PostApiV4ProjectsIdMergeRequestsMergeRequestIidTimeEstimate =
  Gitlabc_components_postapiv4projectsidmergerequestsmergerequestiidtimeestimate

module PostApiV4ProjectsIdPackagesComposer = Gitlabc_components_postapiv4projectsidpackagescomposer

module PostApiV4ProjectsIdPackagesHelmApiChannelCharts =
  Gitlabc_components_postapiv4projectsidpackageshelmapichannelcharts

module PostApiV4ProjectsIdPackagesProtectionRules =
  Gitlabc_components_postapiv4projectsidpackagesprotectionrules

module PostApiV4ProjectsIdPackagesPypi = Gitlabc_components_postapiv4projectsidpackagespypi

module PostApiV4ProjectsIdPackagesRubygemsApiV1Gems =
  Gitlabc_components_postapiv4projectsidpackagesrubygemsapiv1gems

module PostApiV4ProjectsIdPagesDomains = Gitlabc_components_postapiv4projectsidpagesdomains
module PostApiV4ProjectsIdPipeline = Gitlabc_components_postapiv4projectsidpipeline

module PostApiV4ProjectsIdPipelineSchedules =
  Gitlabc_components_postapiv4projectsidpipelineschedules

module PostApiV4ProjectsIdPipelineSchedulesPipelineScheduleIdVariables =
  Gitlabc_components_postapiv4projectsidpipelineschedulespipelinescheduleidvariables

module PostApiV4ProjectsIdProtectedBranches =
  Gitlabc_components_postapiv4projectsidprotectedbranches

module PostApiV4ProjectsIdProtectedTags = Gitlabc_components_postapiv4projectsidprotectedtags

module PostApiV4ProjectsIdRegistryProtectionRepositoryRules =
  Gitlabc_components_postapiv4projectsidregistryprotectionrepositoryrules

module PostApiV4ProjectsIdReleases = Gitlabc_components_postapiv4projectsidreleases

module PostApiV4ProjectsIdReleasesTagNameAssetsLinks =
  Gitlabc_components_postapiv4projectsidreleasestagnameassetslinks

module PostApiV4ProjectsIdRemoteMirrors = Gitlabc_components_postapiv4projectsidremotemirrors

module PostApiV4ProjectsIdRepositoryBranches =
  Gitlabc_components_postapiv4projectsidrepositorybranches

module PostApiV4ProjectsIdRepositoryChangelog =
  Gitlabc_components_postapiv4projectsidrepositorychangelog

module PostApiV4ProjectsIdRepositoryCommits =
  Gitlabc_components_postapiv4projectsidrepositorycommits

module PostApiV4ProjectsIdRepositoryCommitsShaCherryPick =
  Gitlabc_components_postapiv4projectsidrepositorycommitsshacherrypick

module PostApiV4ProjectsIdRepositoryCommitsShaComments =
  Gitlabc_components_postapiv4projectsidrepositorycommitsshacomments

module PostApiV4ProjectsIdRepositoryCommitsShaRevert =
  Gitlabc_components_postapiv4projectsidrepositorycommitssharevert

module PostApiV4ProjectsIdRepositoryFilesFilePath =
  Gitlabc_components_postapiv4projectsidrepositoryfilesfilepath

module PostApiV4ProjectsIdRepositoryStorageMoves =
  Gitlabc_components_postapiv4projectsidrepositorystoragemoves

module PostApiV4ProjectsIdRepositoryTags = Gitlabc_components_postapiv4projectsidrepositorytags
module PostApiV4ProjectsIdRunners = Gitlabc_components_postapiv4projectsidrunners
module PostApiV4ProjectsIdSecureFiles = Gitlabc_components_postapiv4projectsidsecurefiles

module PostApiV4ProjectsIdServicesMattermostSlashCommandsTrigger =
  Gitlabc_components_postapiv4projectsidservicesmattermostslashcommandstrigger

module PostApiV4ProjectsIdServicesSlackSlashCommandsTrigger =
  Gitlabc_components_postapiv4projectsidservicesslackslashcommandstrigger

module PostApiV4ProjectsIdShare = Gitlabc_components_postapiv4projectsidshare
module PostApiV4ProjectsIdSnippets = Gitlabc_components_postapiv4projectsidsnippets

module PostApiV4ProjectsIdSnippetsSnippetIdAwardEmoji =
  Gitlabc_components_postapiv4projectsidsnippetssnippetidawardemoji

module PostApiV4ProjectsIdSnippetsSnippetIdNotesNoteIdAwardEmoji =
  Gitlabc_components_postapiv4projectsidsnippetssnippetidnotesnoteidawardemoji

module PostApiV4ProjectsIdStatusesSha = Gitlabc_components_postapiv4projectsidstatusessha

module PostApiV4ProjectsIdTerraformStateNameLock =
  Gitlabc_components_postapiv4projectsidterraformstatenamelock

module PostApiV4ProjectsIdTriggers = Gitlabc_components_postapiv4projectsidtriggers
module PostApiV4ProjectsIdUploads = Gitlabc_components_postapiv4projectsiduploads
module PostApiV4ProjectsIdVariables = Gitlabc_components_postapiv4projectsidvariables
module PostApiV4ProjectsIdWikis = Gitlabc_components_postapiv4projectsidwikis
module PostApiV4ProjectsIdWikisAttachments = Gitlabc_components_postapiv4projectsidwikisattachments
module PostApiV4ProjectsUserUserId = Gitlabc_components_postapiv4projectsuseruserid
module PostApiV4Runners = Gitlabc_components_postapiv4runners

module PostApiV4RunnersResetAuthenticationToken =
  Gitlabc_components_postapiv4runnersresetauthenticationtoken

module PostApiV4RunnersVerify = Gitlabc_components_postapiv4runnersverify
module PostApiV4UserEmails = Gitlabc_components_postapiv4useremails
module PostApiV4UserGpgKeys = Gitlabc_components_postapiv4usergpgkeys
module PostApiV4UserKeys = Gitlabc_components_postapiv4userkeys
module PostApiV4UserPersonalAccessTokens = Gitlabc_components_postapiv4userpersonalaccesstokens
module PostApiV4UserRunners = Gitlabc_components_postapiv4userrunners
module PostApiV4Users = Gitlabc_components_postapiv4users
module PostApiV4UsersIdEmails = Gitlabc_components_postapiv4usersidemails
module PostApiV4UsersIdGpgKeys = Gitlabc_components_postapiv4usersidgpgkeys

module PostApiV4UsersUserIdImpersonationTokens =
  Gitlabc_components_postapiv4usersuseridimpersonationtokens

module PostApiV4UsersUserIdKeys = Gitlabc_components_postapiv4usersuseridkeys

module PostApiV4UsersUserIdPersonalAccessTokens =
  Gitlabc_components_postapiv4usersuseridpersonalaccesstokens

module PutApiV4AdminBatchedBackgroundMigrationsIdPause =
  Gitlabc_components_putapiv4adminbatchedbackgroundmigrationsidpause

module PutApiV4AdminBatchedBackgroundMigrationsIdResume =
  Gitlabc_components_putapiv4adminbatchedbackgroundmigrationsidresume

module PutApiV4AdminCiVariablesKey = Gitlabc_components_putapiv4admincivariableskey
module PutApiV4AdminClustersClusterId = Gitlabc_components_putapiv4adminclustersclusterid
module PutApiV4GroupsId = Gitlabc_components_putapiv4groupsid

module PutApiV4GroupsIdAccessRequestsUserIdApprove =
  Gitlabc_components_putapiv4groupsidaccessrequestsuseridapprove

module PutApiV4GroupsIdBadgesBadgeId = Gitlabc_components_putapiv4groupsidbadgesbadgeid
module PutApiV4GroupsIdClustersClusterId = Gitlabc_components_putapiv4groupsidclustersclusterid
module PutApiV4GroupsIdCustomAttributesKey = Gitlabc_components_putapiv4groupsidcustomattributeskey

module PutApiV4GroupsIdDebianDistributionsCodename =
  Gitlabc_components_putapiv4groupsiddebiandistributionscodename

module PutApiV4GroupsIdIntegrationsAppleAppStore =
  Gitlabc_components_putapiv4groupsidintegrationsappleappstore

module PutApiV4GroupsIdIntegrationsAsana = Gitlabc_components_putapiv4groupsidintegrationsasana

module PutApiV4GroupsIdIntegrationsAssembla =
  Gitlabc_components_putapiv4groupsidintegrationsassembla

module PutApiV4GroupsIdIntegrationsBamboo = Gitlabc_components_putapiv4groupsidintegrationsbamboo

module PutApiV4GroupsIdIntegrationsBugzilla =
  Gitlabc_components_putapiv4groupsidintegrationsbugzilla

module PutApiV4GroupsIdIntegrationsBuildkite =
  Gitlabc_components_putapiv4groupsidintegrationsbuildkite

module PutApiV4GroupsIdIntegrationsCampfire =
  Gitlabc_components_putapiv4groupsidintegrationscampfire

module PutApiV4GroupsIdIntegrationsClickup = Gitlabc_components_putapiv4groupsidintegrationsclickup

module PutApiV4GroupsIdIntegrationsConfluence =
  Gitlabc_components_putapiv4groupsidintegrationsconfluence

module PutApiV4GroupsIdIntegrationsCustomIssueTracker =
  Gitlabc_components_putapiv4groupsidintegrationscustomissuetracker

module PutApiV4GroupsIdIntegrationsDatadog = Gitlabc_components_putapiv4groupsidintegrationsdatadog

module PutApiV4GroupsIdIntegrationsDiffblueCover =
  Gitlabc_components_putapiv4groupsidintegrationsdiffbluecover

module PutApiV4GroupsIdIntegrationsDiscord = Gitlabc_components_putapiv4groupsidintegrationsdiscord
module PutApiV4GroupsIdIntegrationsDroneCi = Gitlabc_components_putapiv4groupsidintegrationsdroneci

module PutApiV4GroupsIdIntegrationsEmailsOnPush =
  Gitlabc_components_putapiv4groupsidintegrationsemailsonpush

module PutApiV4GroupsIdIntegrationsEwm = Gitlabc_components_putapiv4groupsidintegrationsewm

module PutApiV4GroupsIdIntegrationsExternalWiki =
  Gitlabc_components_putapiv4groupsidintegrationsexternalwiki

module PutApiV4GroupsIdIntegrationsGitGuardian =
  Gitlabc_components_putapiv4groupsidintegrationsgitguardian

module PutApiV4GroupsIdIntegrationsGithub = Gitlabc_components_putapiv4groupsidintegrationsgithub

module PutApiV4GroupsIdIntegrationsGitlabSlackApplication =
  Gitlabc_components_putapiv4groupsidintegrationsgitlabslackapplication

module PutApiV4GroupsIdIntegrationsGoogleCloudPlatformArtifactRegistry =
  Gitlabc_components_putapiv4groupsidintegrationsgooglecloudplatformartifactregistry

module PutApiV4GroupsIdIntegrationsGoogleCloudPlatformWorkloadIdentityFederation =
  Gitlabc_components_putapiv4groupsidintegrationsgooglecloudplatformworkloadidentityfederation

module PutApiV4GroupsIdIntegrationsGooglePlay =
  Gitlabc_components_putapiv4groupsidintegrationsgoogleplay

module PutApiV4GroupsIdIntegrationsHangoutsChat =
  Gitlabc_components_putapiv4groupsidintegrationshangoutschat

module PutApiV4GroupsIdIntegrationsHarbor = Gitlabc_components_putapiv4groupsidintegrationsharbor
module PutApiV4GroupsIdIntegrationsIrker = Gitlabc_components_putapiv4groupsidintegrationsirker
module PutApiV4GroupsIdIntegrationsJenkins = Gitlabc_components_putapiv4groupsidintegrationsjenkins
module PutApiV4GroupsIdIntegrationsJira = Gitlabc_components_putapiv4groupsidintegrationsjira

module PutApiV4GroupsIdIntegrationsJiraCloudApp =
  Gitlabc_components_putapiv4groupsidintegrationsjiracloudapp

module PutApiV4GroupsIdIntegrationsMatrix = Gitlabc_components_putapiv4groupsidintegrationsmatrix

module PutApiV4GroupsIdIntegrationsMattermost =
  Gitlabc_components_putapiv4groupsidintegrationsmattermost

module PutApiV4GroupsIdIntegrationsMattermostSlashCommands =
  Gitlabc_components_putapiv4groupsidintegrationsmattermostslashcommands

module PutApiV4GroupsIdIntegrationsMicrosoftTeams =
  Gitlabc_components_putapiv4groupsidintegrationsmicrosoftteams

module PutApiV4GroupsIdIntegrationsMockCi = Gitlabc_components_putapiv4groupsidintegrationsmockci

module PutApiV4GroupsIdIntegrationsMockMonitoring =
  Gitlabc_components_putapiv4groupsidintegrationsmockmonitoring

module PutApiV4GroupsIdIntegrationsPackagist =
  Gitlabc_components_putapiv4groupsidintegrationspackagist

module PutApiV4GroupsIdIntegrationsPhorge = Gitlabc_components_putapiv4groupsidintegrationsphorge

module PutApiV4GroupsIdIntegrationsPipelinesEmail =
  Gitlabc_components_putapiv4groupsidintegrationspipelinesemail

module PutApiV4GroupsIdIntegrationsPivotaltracker =
  Gitlabc_components_putapiv4groupsidintegrationspivotaltracker

module PutApiV4GroupsIdIntegrationsPumble = Gitlabc_components_putapiv4groupsidintegrationspumble

module PutApiV4GroupsIdIntegrationsPushover =
  Gitlabc_components_putapiv4groupsidintegrationspushover

module PutApiV4GroupsIdIntegrationsRedmine = Gitlabc_components_putapiv4groupsidintegrationsredmine
module PutApiV4GroupsIdIntegrationsSlack = Gitlabc_components_putapiv4groupsidintegrationsslack

module PutApiV4GroupsIdIntegrationsSlackSlashCommands =
  Gitlabc_components_putapiv4groupsidintegrationsslackslashcommands

module PutApiV4GroupsIdIntegrationsSquashTm =
  Gitlabc_components_putapiv4groupsidintegrationssquashtm

module PutApiV4GroupsIdIntegrationsTeamcity =
  Gitlabc_components_putapiv4groupsidintegrationsteamcity

module PutApiV4GroupsIdIntegrationsTelegram =
  Gitlabc_components_putapiv4groupsidintegrationstelegram

module PutApiV4GroupsIdIntegrationsUnifyCircuit =
  Gitlabc_components_putapiv4groupsidintegrationsunifycircuit

module PutApiV4GroupsIdIntegrationsWebexTeams =
  Gitlabc_components_putapiv4groupsidintegrationswebexteams

module PutApiV4GroupsIdIntegrationsYoutrack =
  Gitlabc_components_putapiv4groupsidintegrationsyoutrack

module PutApiV4GroupsIdIntegrationsZentao = Gitlabc_components_putapiv4groupsidintegrationszentao
module PutApiV4GroupsIdInvitationsEmail = Gitlabc_components_putapiv4groupsidinvitationsemail
module PutApiV4GroupsIdMembersUserId = Gitlabc_components_putapiv4groupsidmembersuserid
module PutApiV4GroupsIdMembersUserIdState = Gitlabc_components_putapiv4groupsidmembersuseridstate

module PutApiV4GroupsIdPackagesNpmPackage_packageNameDistTagsTag =
  Gitlabc_components_putapiv4groupsidpackagesnpmpackage_packagenamedisttagstag

module PutApiV4GroupsIdVariablesKey = Gitlabc_components_putapiv4groupsidvariableskey
module PutApiV4GroupsIdWikisSlug = Gitlabc_components_putapiv4groupsidwikisslug
module PutApiV4ProjectsId = Gitlabc_components_putapiv4projectsid

module PutApiV4ProjectsIdAccessRequestsUserIdApprove =
  Gitlabc_components_putapiv4projectsidaccessrequestsuseridapprove

module PutApiV4ProjectsIdBadgesBadgeId = Gitlabc_components_putapiv4projectsidbadgesbadgeid
module PutApiV4ProjectsIdClustersClusterId = Gitlabc_components_putapiv4projectsidclustersclusterid

module PutApiV4ProjectsIdCustomAttributesKey =
  Gitlabc_components_putapiv4projectsidcustomattributeskey

module PutApiV4ProjectsIdDebianDistributionsCodename =
  Gitlabc_components_putapiv4projectsiddebiandistributionscodename

module PutApiV4ProjectsIdDeployKeysKeyId = Gitlabc_components_putapiv4projectsiddeploykeyskeyid

module PutApiV4ProjectsIdDeploymentsDeploymentId =
  Gitlabc_components_putapiv4projectsiddeploymentsdeploymentid

module PutApiV4ProjectsIdEnvironmentsEnvironmentId =
  Gitlabc_components_putapiv4projectsidenvironmentsenvironmentid

module PutApiV4ProjectsIdErrorTrackingSettings =
  Gitlabc_components_putapiv4projectsiderrortrackingsettings

module PutApiV4ProjectsIdFeatureFlagsFeatureFlagName =
  Gitlabc_components_putapiv4projectsidfeatureflagsfeatureflagname

module PutApiV4ProjectsIdFeatureFlagsUserListsIid =
  Gitlabc_components_putapiv4projectsidfeatureflagsuserlistsiid

module PutApiV4ProjectsIdFreezePeriodsFreezePeriodId =
  Gitlabc_components_putapiv4projectsidfreezeperiodsfreezeperiodid

module PutApiV4ProjectsIdHooksHookId = Gitlabc_components_putapiv4projectsidhookshookid

module PutApiV4ProjectsIdHooksHookIdCustomHeadersKey =
  Gitlabc_components_putapiv4projectsidhookshookidcustomheaderskey

module PutApiV4ProjectsIdHooksHookIdUrlVariablesKey =
  Gitlabc_components_putapiv4projectsidhookshookidurlvariableskey

module PutApiV4ProjectsIdIntegrationsAppleAppStore =
  Gitlabc_components_putapiv4projectsidintegrationsappleappstore

module PutApiV4ProjectsIdIntegrationsAsana = Gitlabc_components_putapiv4projectsidintegrationsasana

module PutApiV4ProjectsIdIntegrationsAssembla =
  Gitlabc_components_putapiv4projectsidintegrationsassembla

module PutApiV4ProjectsIdIntegrationsBamboo =
  Gitlabc_components_putapiv4projectsidintegrationsbamboo

module PutApiV4ProjectsIdIntegrationsBugzilla =
  Gitlabc_components_putapiv4projectsidintegrationsbugzilla

module PutApiV4ProjectsIdIntegrationsBuildkite =
  Gitlabc_components_putapiv4projectsidintegrationsbuildkite

module PutApiV4ProjectsIdIntegrationsCampfire =
  Gitlabc_components_putapiv4projectsidintegrationscampfire

module PutApiV4ProjectsIdIntegrationsClickup =
  Gitlabc_components_putapiv4projectsidintegrationsclickup

module PutApiV4ProjectsIdIntegrationsConfluence =
  Gitlabc_components_putapiv4projectsidintegrationsconfluence

module PutApiV4ProjectsIdIntegrationsCustomIssueTracker =
  Gitlabc_components_putapiv4projectsidintegrationscustomissuetracker

module PutApiV4ProjectsIdIntegrationsDatadog =
  Gitlabc_components_putapiv4projectsidintegrationsdatadog

module PutApiV4ProjectsIdIntegrationsDiffblueCover =
  Gitlabc_components_putapiv4projectsidintegrationsdiffbluecover

module PutApiV4ProjectsIdIntegrationsDiscord =
  Gitlabc_components_putapiv4projectsidintegrationsdiscord

module PutApiV4ProjectsIdIntegrationsDroneCi =
  Gitlabc_components_putapiv4projectsidintegrationsdroneci

module PutApiV4ProjectsIdIntegrationsEmailsOnPush =
  Gitlabc_components_putapiv4projectsidintegrationsemailsonpush

module PutApiV4ProjectsIdIntegrationsEwm = Gitlabc_components_putapiv4projectsidintegrationsewm

module PutApiV4ProjectsIdIntegrationsExternalWiki =
  Gitlabc_components_putapiv4projectsidintegrationsexternalwiki

module PutApiV4ProjectsIdIntegrationsGitGuardian =
  Gitlabc_components_putapiv4projectsidintegrationsgitguardian

module PutApiV4ProjectsIdIntegrationsGithub =
  Gitlabc_components_putapiv4projectsidintegrationsgithub

module PutApiV4ProjectsIdIntegrationsGitlabSlackApplication =
  Gitlabc_components_putapiv4projectsidintegrationsgitlabslackapplication

module PutApiV4ProjectsIdIntegrationsGoogleCloudPlatformArtifactRegistry =
  Gitlabc_components_putapiv4projectsidintegrationsgooglecloudplatformartifactregistry

module PutApiV4ProjectsIdIntegrationsGoogleCloudPlatformWorkloadIdentityFederation =
  Gitlabc_components_putapiv4projectsidintegrationsgooglecloudplatformworkloadidentityfederation

module PutApiV4ProjectsIdIntegrationsGooglePlay =
  Gitlabc_components_putapiv4projectsidintegrationsgoogleplay

module PutApiV4ProjectsIdIntegrationsHangoutsChat =
  Gitlabc_components_putapiv4projectsidintegrationshangoutschat

module PutApiV4ProjectsIdIntegrationsHarbor =
  Gitlabc_components_putapiv4projectsidintegrationsharbor

module PutApiV4ProjectsIdIntegrationsIrker = Gitlabc_components_putapiv4projectsidintegrationsirker

module PutApiV4ProjectsIdIntegrationsJenkins =
  Gitlabc_components_putapiv4projectsidintegrationsjenkins

module PutApiV4ProjectsIdIntegrationsJira = Gitlabc_components_putapiv4projectsidintegrationsjira

module PutApiV4ProjectsIdIntegrationsJiraCloudApp =
  Gitlabc_components_putapiv4projectsidintegrationsjiracloudapp

module PutApiV4ProjectsIdIntegrationsMatrix =
  Gitlabc_components_putapiv4projectsidintegrationsmatrix

module PutApiV4ProjectsIdIntegrationsMattermost =
  Gitlabc_components_putapiv4projectsidintegrationsmattermost

module PutApiV4ProjectsIdIntegrationsMattermostSlashCommands =
  Gitlabc_components_putapiv4projectsidintegrationsmattermostslashcommands

module PutApiV4ProjectsIdIntegrationsMicrosoftTeams =
  Gitlabc_components_putapiv4projectsidintegrationsmicrosoftteams

module PutApiV4ProjectsIdIntegrationsMockCi =
  Gitlabc_components_putapiv4projectsidintegrationsmockci

module PutApiV4ProjectsIdIntegrationsMockMonitoring =
  Gitlabc_components_putapiv4projectsidintegrationsmockmonitoring

module PutApiV4ProjectsIdIntegrationsPackagist =
  Gitlabc_components_putapiv4projectsidintegrationspackagist

module PutApiV4ProjectsIdIntegrationsPhorge =
  Gitlabc_components_putapiv4projectsidintegrationsphorge

module PutApiV4ProjectsIdIntegrationsPipelinesEmail =
  Gitlabc_components_putapiv4projectsidintegrationspipelinesemail

module PutApiV4ProjectsIdIntegrationsPivotaltracker =
  Gitlabc_components_putapiv4projectsidintegrationspivotaltracker

module PutApiV4ProjectsIdIntegrationsPumble =
  Gitlabc_components_putapiv4projectsidintegrationspumble

module PutApiV4ProjectsIdIntegrationsPushover =
  Gitlabc_components_putapiv4projectsidintegrationspushover

module PutApiV4ProjectsIdIntegrationsRedmine =
  Gitlabc_components_putapiv4projectsidintegrationsredmine

module PutApiV4ProjectsIdIntegrationsSlack = Gitlabc_components_putapiv4projectsidintegrationsslack

module PutApiV4ProjectsIdIntegrationsSlackSlashCommands =
  Gitlabc_components_putapiv4projectsidintegrationsslackslashcommands

module PutApiV4ProjectsIdIntegrationsSquashTm =
  Gitlabc_components_putapiv4projectsidintegrationssquashtm

module PutApiV4ProjectsIdIntegrationsTeamcity =
  Gitlabc_components_putapiv4projectsidintegrationsteamcity

module PutApiV4ProjectsIdIntegrationsTelegram =
  Gitlabc_components_putapiv4projectsidintegrationstelegram

module PutApiV4ProjectsIdIntegrationsUnifyCircuit =
  Gitlabc_components_putapiv4projectsidintegrationsunifycircuit

module PutApiV4ProjectsIdIntegrationsWebexTeams =
  Gitlabc_components_putapiv4projectsidintegrationswebexteams

module PutApiV4ProjectsIdIntegrationsYoutrack =
  Gitlabc_components_putapiv4projectsidintegrationsyoutrack

module PutApiV4ProjectsIdIntegrationsZentao =
  Gitlabc_components_putapiv4projectsidintegrationszentao

module PutApiV4ProjectsIdInvitationsEmail = Gitlabc_components_putapiv4projectsidinvitationsemail
module PutApiV4ProjectsIdMembersUserId = Gitlabc_components_putapiv4projectsidmembersuserid

module PutApiV4ProjectsIdMergeRequestsMergeRequestIid =
  Gitlabc_components_putapiv4projectsidmergerequestsmergerequestiid

module PutApiV4ProjectsIdMergeRequestsMergeRequestIidDraftNotesDraftNoteId =
  Gitlabc_components_putapiv4projectsidmergerequestsmergerequestiiddraftnotesdraftnoteid

module PutApiV4ProjectsIdMergeRequestsMergeRequestIidMerge =
  Gitlabc_components_putapiv4projectsidmergerequestsmergerequestiidmerge

module PutApiV4ProjectsIdMergeRequestsMergeRequestIidRebase =
  Gitlabc_components_putapiv4projectsidmergerequestsmergerequestiidrebase

module
  PutApiV4ProjectsIdPackagesConanV1FilesPackageNamePackageVersionPackageUsernamePackageChannelRecipeRevisionExportFileName =
  Gitlabc_components_putapiv4projectsidpackagesconanv1filespackagenamepackageversionpackageusernamepackagechannelreciperevisionexportfilename

module
  PutApiV4ProjectsIdPackagesConanV1FilesPackageNamePackageVersionPackageUsernamePackageChannelRecipeRevisionPackageConanPackageReferencePackageRevisionFileName =
  Gitlabc_components_putapiv4projectsidpackagesconanv1filespackagenamepackageversionpackageusernamepackagechannelreciperevisionpackageconanpackagereferencepackagerevisionfilename

module PutApiV4ProjectsIdPackagesDebianFileName =
  Gitlabc_components_putapiv4projectsidpackagesdebianfilename

module PutApiV4ProjectsIdPackagesDebianFileNameAuthorize =
  Gitlabc_components_putapiv4projectsidpackagesdebianfilenameauthorize

module PutApiV4ProjectsIdPackagesGenericPackageName_packageVersion__path_FileName =
  Gitlabc_components_putapiv4projectsidpackagesgenericpackagename_packageversion__path_filename

module PutApiV4ProjectsIdPackagesGenericPackageName_packageVersion__path_FileNameAuthorize =
  Gitlabc_components_putapiv4projectsidpackagesgenericpackagename_packageversion__path_filenameauthorize

module PutApiV4ProjectsIdPackagesMaven_pathFileName =
  Gitlabc_components_putapiv4projectsidpackagesmaven_pathfilename

module PutApiV4ProjectsIdPackagesMaven_pathFileNameAuthorize =
  Gitlabc_components_putapiv4projectsidpackagesmaven_pathfilenameauthorize

module PutApiV4ProjectsIdPackagesMlModelsModelVersionIdFiles__path_FileName =
  Gitlabc_components_putapiv4projectsidpackagesmlmodelsmodelversionidfiles__path_filename

module PutApiV4ProjectsIdPackagesMlModelsModelVersionIdFiles__path_FileNameAuthorize =
  Gitlabc_components_putapiv4projectsidpackagesmlmodelsmodelversionidfiles__path_filenameauthorize

module PutApiV4ProjectsIdPackagesNpmPackage_packageNameDistTagsTag =
  Gitlabc_components_putapiv4projectsidpackagesnpmpackage_packagenamedisttagstag

module PutApiV4ProjectsIdPackagesNpmPackageName =
  Gitlabc_components_putapiv4projectsidpackagesnpmpackagename

module PutApiV4ProjectsIdPackagesNuget = Gitlabc_components_putapiv4projectsidpackagesnuget

module PutApiV4ProjectsIdPackagesNugetSymbolpackage =
  Gitlabc_components_putapiv4projectsidpackagesnugetsymbolpackage

module PutApiV4ProjectsIdPackagesNugetV2 = Gitlabc_components_putapiv4projectsidpackagesnugetv2

module PutApiV4ProjectsIdPackagesTerraformModulesModuleNameModuleSystem_moduleVersionFileAuthorize =
  Gitlabc_components_putapiv4projectsidpackagesterraformmodulesmodulenamemodulesystem_moduleversionfileauthorize

module PutApiV4ProjectsIdPagesDomainsDomain =
  Gitlabc_components_putapiv4projectsidpagesdomainsdomain

module PutApiV4ProjectsIdPipelineSchedulesPipelineScheduleId =
  Gitlabc_components_putapiv4projectsidpipelineschedulespipelinescheduleid

module PutApiV4ProjectsIdPipelineSchedulesPipelineScheduleIdVariablesKey =
  Gitlabc_components_putapiv4projectsidpipelineschedulespipelinescheduleidvariableskey

module PutApiV4ProjectsIdPipelinesPipelineIdMetadata =
  Gitlabc_components_putapiv4projectsidpipelinespipelineidmetadata

module PutApiV4ProjectsIdReleasesTagName = Gitlabc_components_putapiv4projectsidreleasestagname

module PutApiV4ProjectsIdReleasesTagNameAssetsLinksLinkId =
  Gitlabc_components_putapiv4projectsidreleasestagnameassetslinkslinkid

module PutApiV4ProjectsIdRemoteMirrorsMirrorId =
  Gitlabc_components_putapiv4projectsidremotemirrorsmirrorid

module PutApiV4ProjectsIdRepositoryBranchesBranchProtect =
  Gitlabc_components_putapiv4projectsidrepositorybranchesbranchprotect

module PutApiV4ProjectsIdRepositoryFilesFilePath =
  Gitlabc_components_putapiv4projectsidrepositoryfilesfilepath

module PutApiV4ProjectsIdRepositorySubmodulesSubmodule =
  Gitlabc_components_putapiv4projectsidrepositorysubmodulessubmodule

module PutApiV4ProjectsIdResourceGroupsKey = Gitlabc_components_putapiv4projectsidresourcegroupskey

module PutApiV4ProjectsIdServicesAppleAppStore =
  Gitlabc_components_putapiv4projectsidservicesappleappstore

module PutApiV4ProjectsIdServicesAsana = Gitlabc_components_putapiv4projectsidservicesasana
module PutApiV4ProjectsIdServicesAssembla = Gitlabc_components_putapiv4projectsidservicesassembla
module PutApiV4ProjectsIdServicesBamboo = Gitlabc_components_putapiv4projectsidservicesbamboo
module PutApiV4ProjectsIdServicesBugzilla = Gitlabc_components_putapiv4projectsidservicesbugzilla
module PutApiV4ProjectsIdServicesBuildkite = Gitlabc_components_putapiv4projectsidservicesbuildkite
module PutApiV4ProjectsIdServicesCampfire = Gitlabc_components_putapiv4projectsidservicescampfire
module PutApiV4ProjectsIdServicesClickup = Gitlabc_components_putapiv4projectsidservicesclickup

module PutApiV4ProjectsIdServicesConfluence =
  Gitlabc_components_putapiv4projectsidservicesconfluence

module PutApiV4ProjectsIdServicesCustomIssueTracker =
  Gitlabc_components_putapiv4projectsidservicescustomissuetracker

module PutApiV4ProjectsIdServicesDatadog = Gitlabc_components_putapiv4projectsidservicesdatadog

module PutApiV4ProjectsIdServicesDiffblueCover =
  Gitlabc_components_putapiv4projectsidservicesdiffbluecover

module PutApiV4ProjectsIdServicesDiscord = Gitlabc_components_putapiv4projectsidservicesdiscord
module PutApiV4ProjectsIdServicesDroneCi = Gitlabc_components_putapiv4projectsidservicesdroneci

module PutApiV4ProjectsIdServicesEmailsOnPush =
  Gitlabc_components_putapiv4projectsidservicesemailsonpush

module PutApiV4ProjectsIdServicesEwm = Gitlabc_components_putapiv4projectsidservicesewm

module PutApiV4ProjectsIdServicesExternalWiki =
  Gitlabc_components_putapiv4projectsidservicesexternalwiki

module PutApiV4ProjectsIdServicesGitGuardian =
  Gitlabc_components_putapiv4projectsidservicesgitguardian

module PutApiV4ProjectsIdServicesGithub = Gitlabc_components_putapiv4projectsidservicesgithub

module PutApiV4ProjectsIdServicesGitlabSlackApplication =
  Gitlabc_components_putapiv4projectsidservicesgitlabslackapplication

module PutApiV4ProjectsIdServicesGoogleCloudPlatformArtifactRegistry =
  Gitlabc_components_putapiv4projectsidservicesgooglecloudplatformartifactregistry

module PutApiV4ProjectsIdServicesGoogleCloudPlatformWorkloadIdentityFederation =
  Gitlabc_components_putapiv4projectsidservicesgooglecloudplatformworkloadidentityfederation

module PutApiV4ProjectsIdServicesGooglePlay =
  Gitlabc_components_putapiv4projectsidservicesgoogleplay

module PutApiV4ProjectsIdServicesHangoutsChat =
  Gitlabc_components_putapiv4projectsidserviceshangoutschat

module PutApiV4ProjectsIdServicesHarbor = Gitlabc_components_putapiv4projectsidservicesharbor
module PutApiV4ProjectsIdServicesIrker = Gitlabc_components_putapiv4projectsidservicesirker
module PutApiV4ProjectsIdServicesJenkins = Gitlabc_components_putapiv4projectsidservicesjenkins
module PutApiV4ProjectsIdServicesJira = Gitlabc_components_putapiv4projectsidservicesjira

module PutApiV4ProjectsIdServicesJiraCloudApp =
  Gitlabc_components_putapiv4projectsidservicesjiracloudapp

module PutApiV4ProjectsIdServicesMatrix = Gitlabc_components_putapiv4projectsidservicesmatrix

module PutApiV4ProjectsIdServicesMattermost =
  Gitlabc_components_putapiv4projectsidservicesmattermost

module PutApiV4ProjectsIdServicesMattermostSlashCommands =
  Gitlabc_components_putapiv4projectsidservicesmattermostslashcommands

module PutApiV4ProjectsIdServicesMicrosoftTeams =
  Gitlabc_components_putapiv4projectsidservicesmicrosoftteams

module PutApiV4ProjectsIdServicesMockCi = Gitlabc_components_putapiv4projectsidservicesmockci

module PutApiV4ProjectsIdServicesMockMonitoring =
  Gitlabc_components_putapiv4projectsidservicesmockmonitoring

module PutApiV4ProjectsIdServicesPackagist = Gitlabc_components_putapiv4projectsidservicespackagist
module PutApiV4ProjectsIdServicesPhorge = Gitlabc_components_putapiv4projectsidservicesphorge

module PutApiV4ProjectsIdServicesPipelinesEmail =
  Gitlabc_components_putapiv4projectsidservicespipelinesemail

module PutApiV4ProjectsIdServicesPivotaltracker =
  Gitlabc_components_putapiv4projectsidservicespivotaltracker

module PutApiV4ProjectsIdServicesPumble = Gitlabc_components_putapiv4projectsidservicespumble
module PutApiV4ProjectsIdServicesPushover = Gitlabc_components_putapiv4projectsidservicespushover
module PutApiV4ProjectsIdServicesRedmine = Gitlabc_components_putapiv4projectsidservicesredmine
module PutApiV4ProjectsIdServicesSlack = Gitlabc_components_putapiv4projectsidservicesslack

module PutApiV4ProjectsIdServicesSlackSlashCommands =
  Gitlabc_components_putapiv4projectsidservicesslackslashcommands

module PutApiV4ProjectsIdServicesSquashTm = Gitlabc_components_putapiv4projectsidservicessquashtm
module PutApiV4ProjectsIdServicesTeamcity = Gitlabc_components_putapiv4projectsidservicesteamcity
module PutApiV4ProjectsIdServicesTelegram = Gitlabc_components_putapiv4projectsidservicestelegram

module PutApiV4ProjectsIdServicesUnifyCircuit =
  Gitlabc_components_putapiv4projectsidservicesunifycircuit

module PutApiV4ProjectsIdServicesWebexTeams =
  Gitlabc_components_putapiv4projectsidserviceswebexteams

module PutApiV4ProjectsIdServicesYoutrack = Gitlabc_components_putapiv4projectsidservicesyoutrack
module PutApiV4ProjectsIdServicesZentao = Gitlabc_components_putapiv4projectsidserviceszentao
module PutApiV4ProjectsIdSnippetsSnippetId = Gitlabc_components_putapiv4projectsidsnippetssnippetid
module PutApiV4ProjectsIdTransfer = Gitlabc_components_putapiv4projectsidtransfer
module PutApiV4ProjectsIdTriggersTriggerId = Gitlabc_components_putapiv4projectsidtriggerstriggerid
module PutApiV4ProjectsIdVariablesKey = Gitlabc_components_putapiv4projectsidvariableskey
module PutApiV4ProjectsIdWikisSlug = Gitlabc_components_putapiv4projectsidwikisslug
module PutApiV4RunnersId = Gitlabc_components_putapiv4runnersid
module PutApiV4UserAvatar = Gitlabc_components_putapiv4useravatar
module PutApiV4UserPreferences = Gitlabc_components_putapiv4userpreferences
module PutApiV4UserStatus = Gitlabc_components_putapiv4userstatus

module PutApiV4UserUserIdCreditCardValidation =
  Gitlabc_components_putapiv4useruseridcreditcardvalidation

module PutApiV4UsersId = Gitlabc_components_putapiv4usersid
module PutApiV4UsersIdCustomAttributesKey = Gitlabc_components_putapiv4usersidcustomattributeskey
