#!/usr/bin/env bash
set -euf -o pipefail

# Source config file for base_image
CONFIG_FILE="$(dirname "$0")/../config/base_image_config.sh"
if [[ -f "$CONFIG_FILE" ]]; then
    source "$CONFIG_FILE"
fi

# Set BASE_IMAGE to $1 if provided; otherwise, use the config file's BASE_IMAGE
BASE_IMAGE="${1:-${BASE_IMAGE}}"

echo "BASE_IMAGE=${BASE_IMAGE}"
