#! /usr/bin/env bash
set -euf -o pipefail

release_name=""
github_owner=""
github_repo=""
prev_tag=""
curr_tag=""

while getopts "p:c:o:r:n:" opt; do
    case "${opt}" in
        p)
            prev_tag="${OPTARG}"
            ;;
        c)
            curr_tag="${OPTARG}"
            ;;
        o)
            github_owner="${OPTARG}"
            ;;
        r)
            github_repo="${OPTARG}"
            ;;
        n)
            release_name="${OPTARG}"
            ;;
        *)
            echo "Unknown option" 1>&2
            exit 1
            ;;
    esac
done

if [[ -z "$prev_tag" ]]; then
    echo "Must specify a previous tag (-p)" 1>&2
    exit 1
fi

if [[ -z "$github_owner" ]]; then
    echo "Must specity a repository organization (-o)" 1>&2
    exit 1
fi

if [[ -z "$github_repo" ]]; then
    echo "Must specity a repository name (-r)" 1>&2
    exit 1
fi

if [[ -z "$release_name" ]]; then
    echo "Must specity a release name (-n)" 1>&2
    exit 1
fi

log="$(git log --format='%s' --no-merges "${prev_tag}..${curr_tag}")"

set +e
fixes="$(echo "$log" | grep -E '^(PRO-[0-9]+ ?|[0-9]+ ?)+ FIX ' | sed 's/^/- /')"
refactorings="$(echo "$log" | grep -E '^(PRO-[0-9]+ ?|[0-9]+ ?)+ REFACTOR ' | sed 's/^/- /')"
additions="$(echo "$log" | grep -E '^(PRO-[0-9]+ ?|[0-9]+ ?)+ ADD ' | sed 's/^/- /')"
others="$(echo "$log" | grep -Ev '^(PRO-[0-9]+ ?|[0-9]+ ?)+ (FIX|REFACTOR|ADD) ' | sed 's/^/- /')"
set -e


cat << EOF
# ${release_name}

## New Features and Functionality

${additions}

## Bug Fixes

${fixes}

## Refactorings

${refactorings}

## Other Changes

${others}
EOF
